Propagate exit status code 11 so live-installer can properly exit.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@64894 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/finish-install/debian/postinst b/packages/finish-install/debian/postinst
--- a/packages/finish-install/debian/postinst
+++ b/packages/finish-install/debian/postinst
@@ -27,12 +27,20 @@ for script in "$partsdir"/*; do
 			:
 		else
 			code="$?"
-			if [ "$code" = 10 ]; then
+			case "$code" in
+				10)
 				log "$script backed up"
 				db_progress STOP
 				exit 10
-			fi
-			log "warning: $script returned error code $code"
+				;;
+				11)
+				log "$script has asked to exit installer"
+				exit 11
+				;;
+				*)
+				log "warning: $script returned error code $code"
+				;;
+			esac
 		fi
 	else
 		log "error: Unable to execute $script"
