- Allow unknown dependencies in package-list files to be forced       not to be removed by gen-control, by following them with a bang.       I expect this will be used by third-party modules packages that need to       depend on a udeb from the main kernel package set. Ie, non-free modules.     - copy-modules now uses find to find a module anywhere in the kernel       modules tree.     - Module list files no longer need path info (or extension info!), though       old ones with that info will still work (mostly; not if whole module       subdirs such as sym53c8xx_2 or aic7xxx were listed).     - Modules not in the kernel/ subdir can also be listed now.     - Remove all module path and extension info from kernel-wedge's own       module lists.     - Try to clean up the sym53c8xx_2 / sym53c8xx mess somewhat. It was too       complicated to describe.. Currently both modules are included in       scsi-common-modules if a kernel has both.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@26742 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/kernel/kernel-wedge/commands/copy-modules b/packages/kernel/kernel-wedge/commands/copy-modules
--- a/packages/kernel/kernel-wedge/commands/copy-modules
+++ b/packages/kernel/kernel-wedge/commands/copy-modules
@@ -38,24 +38,33 @@ processmodules() {
 	
 	cp $list $tmpdir/work
 	(
-		while read file; do
-			if echo "$file" | grep -q -- '^#' || [ -z "$file" ]; then
+		while read module; do
+			if echo "$module" | grep -q -- '^#' || [ -z "$module" ]; then
 				continue
 			fi
 
-			if echo "$file" | grep -q -- '^-'; then
+			if echo "$module" | grep -q -- '^-'; then
 				optional=1
-				file=$(echo $file | sed 's/^-//');
+				module=${module#-}
 			else
 				optional=0
 			fi
-			if [ -e $moddir/$file ]; then
-				echo $file
-			elif [ -e $moddir/${file%.o}.ko ]; then
-				echo ${file%.o}.ko
+
+			module=${module##*/} # remove path info
+			module=${module%.*}  # remove extension
+			
+			# Prefer modules in the kernel subdir, but failing
+			# that search the whole thing, to find third-party,
+			# etc modules.
+			match="$(find $moddir/kernel $moddir \
+			            -name $module.o -or -name $module.ko \
+				| head -n 1 | sed "s!$moddir/!!")"
+			
+			if [ -n "$match" ]; then
+				echo $match
 			else
 				if [ "$optional" = 0 ]; then
-					echo "missing module $file" >&2
+					echo "missing module $module" >&2
 					exit 1
 				fi
 			fi
@@ -87,12 +96,6 @@ if [ ! -d $moddir ]; then
 	exit 0
 fi
 	
-if [ "" != "`echo $version | grep ^2.2.`" ]; then
-	kernel_modules=""
-else
-	kernel_modules="/kernel"
-fi
-
 # The directory of modules lists to use.
 if [ -d modules/$arch-$flavour ]; then
 	modlistdir=modules/$arch-$flavour
@@ -158,7 +161,7 @@ for i in $(
 		sort -k 1,1 > $tmpdir/tmpdeps
 
 	# deal with modules marked as optional and other transformations
-	processmodules $tmpdir/module-list/$i $moddir$kernel_modules
+	processmodules $tmpdir/module-list/$i $moddir
 
 	# include dependent modules which are not in a
 	# dependent udeb into module-list/$i
@@ -166,14 +169,14 @@ for i in $(
 
 	if [ -s $tmpdir/module-list/$i ] && dh_listpackages | grep -qx "$i-$version-di"; then
 		# copy kernel modules to package build dir
-		cd $moddir$kernel_modules
+		cd $moddir
 		ret=$( ( (
 			set +e
 			tar cfT - $tmpdir/module-list/$i
 			printf $? >&3
 		) | (
 			set +e
-			dir=$home/debian/$i-$version-di/lib/modules/$installedname$kernel_modules
+			dir=$home/debian/$i-$version-di/lib/modules/$installedname
 			mkdir -p $dir
 			cd $dir
 			tar xf -
