* Joey Hess      - Complain and abort if there is no modules.dep, rather than generating        broken udebs. Closes: #247833
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@14935 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/kernel/kernel-wedge/commands/copy-modules b/packages/kernel/kernel-wedge/commands/copy-modules
--- a/packages/kernel/kernel-wedge/commands/copy-modules
+++ b/packages/kernel/kernel-wedge/commands/copy-modules
@@ -101,6 +101,11 @@ else
 	modlistdir=modules/$arch
 fi
 
+if [ ! -e "$moddir/modules.dep" ]; then
+	echo "no $moddir/modules.dep. This file is required by kernel-wedge" >&2
+	exit 1
+fi
+
 # get module dependencies from modules.dep
 # sort it by field 2
 perl -lne '
