- Add header that includes refernce to script and the date the file was generated - Fix minor error when there are version exceptions
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@52807 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/l10n/calc-release-status b/scripts/l10n/calc-release-status
--- a/scripts/l10n/calc-release-status
+++ b/scripts/l10n/calc-release-status
@@ -36,6 +36,7 @@ set -e
 # Copyright: Frans Pop <fjp@debian.org>, 2008
 
 NUMLEVELS=5
+SUITE=testing
 REPO=svn://svn.debian.org/svn/d-i
 PTAGS=$REPO/tags/packages
 
@@ -44,7 +45,7 @@ NL="
 "
 
 log() {
-	echo "$*"
+	echo "$*" >&2
 }
 error() {
 	echo "E: $*" >&2
@@ -55,7 +56,7 @@ real_contents() {
 	grep -Ev "^(#.*|)[[:space:]]*$" $1
 }
 
-# Use rmadison to get the current version of a package in testing
+# Use rmadison to get the current version of a package in $SUITE
 # Check first if an exception has been defined
 get_version() {
 	local package madison
@@ -75,9 +76,9 @@ get_version() {
 		fi
 	fi
 
-	madison="$(rmadison -s testing $package | grep source)"
+	madison="$(rmadison -s $SUITE $package | grep source)"
 	if [ -z "$madison" ]; then
-		error "error getting madison info for $package for 'testing'"
+		error "error getting madison info for $package for '$SUITE'"
 		exit 1
 	elif [ $(echo "$madison" | wc -l) -gt 1 ]; then
 		error "got multiple lines from madison for $package"
@@ -192,7 +193,13 @@ for p_dir in $(real_contents packages_list | sort); do
 done
 
 log "Calculating statistics..."
-> translation-status
+
+: > translation-status
+echo "# Installer translation status generated by the script:" >> translation-status
+echo "# scripts/l10n/calc-release-status" >> translation-status
+echo "# This file should be updated before every official release." >> translation-status
+echo "# Generated on: $(date -uR)" >> translation-status
+echo "#" >> translation-status
 
 languages="$(echo "$languages" | grep -v "^en$" | sort)"
 for lang in $languages; do
