Added a few error checks
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@29936 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/l10n/l10n-sync b/scripts/l10n/l10n-sync
--- a/scripts/l10n/l10n-sync
+++ b/scripts/l10n/l10n-sync
@@ -398,14 +398,18 @@ cd $DI_COPY/packages
 if [ "$DEBUG" = "Y" ] ; then
   echo -n "Creating the general template.pot file..."
 fi
+# Check that the next msgcat will not fail (otherwise the template.pot would be empty!)
+if ! msgcat $pots >/dev/null ; then
+  svnerr
+fi
 if [ "$DEBUG" = "Y" ] ; then
-  msgcat $pots | sed 's/charset=CHARSET/charset=UTF-8/g' >$DI_COPY/packages/po/template.pot.new
+  msgcat $pots || svnerr | sed 's/charset=CHARSET/charset=UTF-8/g' >$DI_COPY/packages/po/template.pot.new
 else
   msgcat $pots  | sed 's/charset=CHARSET/charset=UTF-8/g'>$DI_COPY/packages/po/template.pot.new 2>/dev/null
 fi
 # We don't want all templates.pot files headers as we don't care about them
 # So we merge the generated file with a simple header.pot file
-if [ -f po/header.pot ] ; then
+if [ -f po/header.pot -a -s po/template.pot.new ] ; then
   msgcat --use-first po/header.pot po/template.pot.new | sed 's/charset=UTF-8/charset=CHARSET/g' > po/template.pot
   rm po/template.pot.new
 else
