Adapt URLs
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@61838 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/l10n/l10n-stats/gen-stats b/scripts/l10n/l10n-stats/gen-stats
--- a/scripts/l10n/l10n-stats/gen-stats
+++ b/scripts/l10n/l10n-stats/gen-stats
@@ -341,7 +341,7 @@ done
 
 fancy_output
 
-wget -q -O $WD/material/spellcheck${LEVEL}.txt http://d-i.alioth.debian.org/spellcheck/level${LEVEL}/latest/stats.txt || echo "Could not fetch spellcheck stats file for level $I."
+wget -q -O $WD/material/spellcheck${LEVEL}.txt http://d-i.debian.org/l10n-spellcheck/level${LEVEL}/latest/stats.txt || echo "Could not fetch spellcheck stats file for level $I."
 
 mkdir $TARGET_DIR/files
 rm -f $TARGET_DIR/.rank.txt$LEVEL
@@ -369,7 +369,7 @@ for dist in testing unstable cvs ; do
 	for lang in `cat $WD/config/languages`; do #run for every language
 #		echo -n "$lang "
 		NAME=`cat $LANG_NAMES | grep "$lang:" | cut -f2 -d: || echo $lang`
-		echo -e "Statistics of $SCRIPTNAME packages for$NAME in $dist:\nRead http://d-i.alioth.debian.org/l10n-stats\n\nOutdated:" >>  $TARGET_DIR/$lang$ext.txt
+		echo -e "Statistics of $SCRIPTNAME packages for$NAME in $dist:\nRead http://d-i.debian.org/l10n-stats\n\nOutdated:" >>  $TARGET_DIR/$lang$ext.txt
 		MISSING=""
 
 		#for total strings of a language
