Avoid duplicating code for testing/unstable tests
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@38583 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/l10n/l10n-stats/gen-stats b/scripts/l10n/l10n-stats/gen-stats
--- a/scripts/l10n/l10n-stats/gen-stats
+++ b/scripts/l10n/l10n-stats/gen-stats
@@ -214,7 +214,7 @@ if [ "$FETCH" ]; then
 	echo -en "$MERKEL_DOWN" > $TARGET_DIR/packages-list
 	date -u >> $TARGET_DIR/packages-list
 
-	for dist in unstable testing ; do
+	for dist in testing unstable ; do
 		echo "  From $dist:"
 		echo "From $dist:" >> $TARGET_DIR/packages-list
 		for pkg in `cat $WD/config/packages.$dist$LEVEL`; do
@@ -273,232 +273,164 @@ else
 
 fi
 
+fancy_output
 
-#check how many strings at all
-TOTALU=0
-LANG=C
-mkdir $TARGET_DIR/POT
-for path in `cat $WD/config/paths$LEVEL`; do
-	test -f $WD/material/packages.unstable$LEVEL/$path/*.pot || continue
-	U=`untranslated $WD/material/packages.unstable$LEVEL/$path/*.pot`
-	cp $WD/material/packages.unstable$LEVEL/$path/*.pot $TARGET_DIR/POT/${path//\//_}.pot
-  	#echo packages/$path/*.pot
-  	#$GETTEXT/msgfmt --statistics packages/$path/*.pot
-  	echo "$path/*.pot has $U untranslated. ($TOTALU)"
-  	#U=`expr $U + 1`
-  	TOTALU=`expr $TOTALU + $U || echo 0`
-	if [ "$TOTALU" = "0" -o -z "$TOTALU" ]; then
-		echo "Error while counting untranslated strings in templates."
-		$GETTEXT/msgfmt --statistics $WD/material/packages.unstable$LEVEL/$path/*.pot
-	#	exit
-	fi
+echo "Computing the number of strings:"
 
-	#backup everylanguage-file to check against debconf-updatepo later
-	for lang in `cat $WD/config/languages`; do
-		test -f $WD/material/packages.unstable$LEVEL/$path/$lang.po || continue
-		cp $WD/material/packages.unstable$LEVEL/$path/$lang.po $WD/material/packages.unstable$LEVEL/$path/$lang.po.orig >/dev/null 2>&1
+for dist in testing unstable ; do
+	echo "  In $dist:"
+	#check how many strings at all
+	TOTALU=0
+	LANG=C
+	mkdir -p $TARGET_DIR/POT
+	for path in `cat $WD/config/paths.$dist$LEVEL`; do
+		test -f $WD/material/packages.$dist$LEVEL/$path/*.pot || continue
+		U=`untranslated $WD/material/packages.$dist$LEVEL/$path/*.pot`
+		
+		# Copy files only for unstable
+		if [ "$dist" = "unstable" ] ; then
+			cp $WD/material/packages.$dist$LEVEL/$path/*.pot $TARGET_DIR/POT/${path//\//_}.pot
+		fi
+		
+	  	echo "      $path/*.pot:  $U"
+
+		TOTALU=`expr $TOTALU + $U || echo 0`
+		if [ "$TOTALU" = "0" -o -z "$TOTALU" ]; then
+			echo "Error while counting untranslated strings in templates."
+			$GETTEXT/msgfmt --statistics $WD/material/packages.$dist$LEVEL/$path/*.pot
+			#	exit
+		fi
+
+		#backup everylanguage-file to check against debconf-updatepo later
+		for lang in `cat $WD/config/languages`; do
+			test -f $WD/material/packages.$dist$LEVEL/$path/$lang.po || continue
+			cp $WD/material/packages.$dist$LEVEL/$path/$lang.po $WD/material/packages.$dist$LEVEL/$path/$lang.po.orig >/dev/null 2>&1
+		done
+
+		(export PODEBCONF_LIB=/home/bubulle/share/intltool-debian; cd $WD/material/packages.$dist$LEVEL/$path/; pwd | grep "debian/po" > /dev/null && ~bubulle/bin/debconf-updatepo-sid )
+
+
 	done
-
-	(export PODEBCONF_LIB=/home/bubulle/share/intltool-debian; cd $WD/material/packages.unstable$LEVEL/$path/; pwd | grep "debian/po" > /dev/null && ~bubulle/bin/debconf-updatepo-sid )
-
-
+	echo "    Total: $TOTALU"
 done
-echo "Total strings: $TOTALU=100%"
 
-# Same for testing
-
-#check how many strings at all
-TOTALU_T=0
-LANG=C
-for path in `cat $WD/config/paths$LEVEL`; do
-	test -f $WD/material/packages.testing$LEVEL/$path/*.pot || continue
-	U=`untranslated $WD/material/packages.testing$LEVEL/$path/*.pot`
-  	#echo packages/$path/*.pot
-  	#$GETTEXT/msgfmt --statistics packages/$path/*.pot
-  	echo "$path/*.pot has $U untranslated. ($TOTALU_T)"
-  	#U=`expr $U + 1`
-  	TOTALU_T=`expr ${TOTALU_T} + $U || echo 0`
-	if [ "$TOTALU_T" = "0" -o -z "$TOTALU_T" ]; then
-		echo "Error while counting untranslated strings in templates."
-		$GETTEXT/msgfmt --statistics $WD/material/packages.testing$LEVEL/$path/*.pot
-	#	exit
-	fi
-
-	#backup everylanguage-file to check against debconf-updatepo later
-	for lang in `cat $WD/config/languages`; do
-		test -f $WD/material/packages.testing$LEVEL/$path/$lang.po || continue
-		cp $WD/material/packages.testing$LEVEL/$path/$lang.po $WD/material/packages.testing$LEVEL/$path/$lang.po.orig >/dev/null 2>&1
-	done
-
-	#run debconf-updatepo to update the po-files
-	#(cd packages$LEVEL/$path/; pwd | grep "debian/po" > /dev/null && $GETTEXT/debconf-updatepo )
-
-	(export PODEBCONF_LIB=/home/bubulle/share/intltool-debian; cd $WD/material/packages.testing$LEVEL/$path/; pwd | grep "debian/po" > /dev/null && ~bubulle/bin/debconf-updatepo-sid )
-
-	#(cd packages/$path/; $GETTEXT/debconf-updatepo > /dev/null 2>&1)
-
-
-done
-echo "Total strings: $TOTALU_T=100%"
+fancy_output
 
 wget -q -O $WD/material/spellcheck${LEVEL}.txt http://d-i.alioth.debian.org/spellcheck/level${LEVEL}/latest/stats.txt || echo "Could not fetch spellcheck stats file for level $I."
 
-
-#now check:
-RANK=""
-
-#following 3 variables for generating the graph. they include all
-#strings of all languages of all packages
-GR_TRANSLATED=0
-GR_FUZZY=0
-GR_UNTRANSLATED=0
 mkdir $TARGET_DIR/files
 rm -f $TARGET_DIR/.rank.txt$LEVEL
 rm -rf $TEMPDIR
-for lang in `cat $WD/config/languages`; do #run for every language
-  	echo -n "$lang..."
-	NAME=`cat $LANG_NAMES | grep "$lang:" | sed "s/://g" || echo $lang`
-  	echo -e $MERKEL_DOWN"Statistics of $SCRIPTNAME packages for $NAME:\nRead http://people.debian.org/~seppy/d-i/translation-status.html\n\nOutdated:" >>  $TARGET_DIR/$lang.txt
-  	echo -e $MERKEL_DOWN"Statistics of $SCRIPTNAME packages in testing for $NAME:\nRead http://people.debian.org/~seppy/d-i/translation-status.html\n\nOutdated:" >>  $TARGET_DIR/$lang.testing.txt
-  	MISSING=""
-  	MISSING_T=""
 
-	#for total strings of a language
-  	TU=0
-  	TT=0
-  	TF=0
-  	TU_T=0
-  	TT_T=0
-  	TF_T=0
- 	for path in `cat config/paths$LEVEL`; do #for every package
-    		if [ -e $WD/material/packages.unstable$LEVEL/$path/$lang.po ]; then #if the file does exist
-      			LASTT=`translator $WD/material/packages.unstable$LEVEL/$path/$lang.po`
 
-			$GETTEXT/msgmerge -U $WD/material/packages.unstable$LEVEL/$path/$lang.po $WD/material/packages.unstable$LEVEL/$path/*.pot > /dev/null 2>&1
-      			SIGNS="  "	
-			#now check if a file has been modified by debconf-updatepo and output a *
-			#for lang in `cat $WD/languages`; do
-			#	test -f packages/$path/$lang.po || continue
-				ORIG=`$GETTEXT/msgfmt --statistics $WD/material/packages.unstable$LEVEL/$path/$lang.po.orig 2>&1`
-				NEW=`$GETTEXT/msgfmt --statistics $WD/material/packages.unstable$LEVEL/$path/$lang.po 2>&1`
+for dist in testing unstable ; do
+	if [ "$dist" = "unstable" ] ; then
+		ext=""
+	else
+		ext=".$dist"
+	fi
+
+	RANK=""
+
+	#following 3 variables for generating the graph. they include all
+	#strings of all languages of all packages
+	GR_TRANSLATED=0
+	GR_FUZZY=0
+	GR_UNTRANSLATED=0
+	for lang in `cat $WD/config/languages`; do #run for every language
+		echo -n "$lang..."
+		NAME=`cat $LANG_NAMES | grep "$lang:" | sed "s/://g" || echo $lang`
+		echo -e $MERKEL_DOWN"Statistics of $SCRIPTNAME packages for $NAME:\nRead http://people.debian.org/~seppy/d-i/translation-status.html\n\nOutdated:" >>  $TARGET_DIR/$lang$dist.txt
+		MISSING=""
+
+		#for total strings of a language
+		TU=0
+		TT=0
+		TF=0
+		for path in `cat config/paths.$dist$LEVEL`; do #for every package
+			if [ -e $WD/material/packages.$dist$LEVEL/$path/$lang.po ]; then #if the file does exist
+				LASTT=`translator $WD/material/packages.unstable$LEVEL/$path/$lang.po`
+
+				$GETTEXT/msgmerge -U $WD/material/packages.$dist$LEVEL/$path/$lang.po $WD/material/packages.$dist$LEVEL/$path/*.pot > /dev/null 2>&1
+      				SIGNS="  "	
+				#now check if a file has been modified by debconf-updatepo and output a *
+				#for lang in `cat $WD/languages`; do
+				#	test -f packages/$path/$lang.po || continue
+					ORIG=`$GETTEXT/msgfmt --statistics $WD/material/packages.$dist$LEVEL/$path/$lang.po.orig 2>&1`
+				NEW=`$GETTEXT/msgfmt --statistics $WD/material/packages.$dist$LEVEL/$path/$lang.po 2>&1`
 				if [ "$ORIG" != "$NEW" ]; then
 					SIGNS="$SIGNS*" #>> $TARGET_DIR/$lang.txt
 				fi
-				#rm -f $WD/material/packages.unstable$LEVEL/$path/$lang.po.orig 
+				#rm -f $WD/material/packages.$dist$LEVEL/$path/$lang.po.orig 
 	
-			#done
-     			$GETTEXT/msgfmt $WD/material/packages.unstable$LEVEL/$path/$lang.po > /dev/null 2>&1|| (echo "$SIGNS!$path/$lang.po [$LASTT]" >> $TARGET_DIR/$lang.txt; touch /tmp/.$LEVEL.error; return 1) || continue
+				#done
+     				$GETTEXT/msgfmt $WD/material/packages.$dist$LEVEL/$path/$lang.po > /dev/null 2>&1|| (echo "$SIGNS!$path/$lang.po [$LASTT]" >> $TARGET_DIR/$lang.txt; touch /tmp/.$LEVEL.error; return 1) || continue
 
-			#strings of this package:
-      			U=`untranslated $WD/material/packages.unstable$LEVEL/$path/$lang.po`
-      			F=`fuzzy $WD/material/packages.unstable$LEVEL/$path/$lang.po`
-     			T=`translated $WD/material/packages.unstable$LEVEL/$path/$lang.po`
-      			test -z "$U" && U=0
-      			test -z "$F" && F=0
-      			test -z "$T" && T=0
+				#strings of this package:
+      				U=`untranslated $WD/material/packages.$dist$LEVEL/$path/$lang.po`
+      				F=`fuzzy $WD/material/packages.$dist$LEVEL/$path/$lang.po`
+     				T=`translated $WD/material/packages.$dist$LEVEL/$path/$lang.po`
+      				test -z "$U" && U=0
+      				test -z "$F" && F=0
+      				test -z "$T" && T=0
 
 
-      			#get infos:
-			TU=`expr $TU + $U`
-      			TT=`expr $TT + $T`
-      			TF=`expr $TF + $F`
+      				#get infos:
+				TU=`expr $TU + $U`
+      				TT=`expr $TT + $T`
+      				TF=`expr $TF + $F`
 
-			#for the graph:
-			GR_TRANSLATED=`expr $GR_TRANSLATED + $TT`
-			GR_UNTRANSLATED=`expr $GR_UNTRANSLATED + $TU`
-			GR_FUZZY=`expr $GR_FUZZY + $TF`
+				#for the graph:
+				GR_TRANSLATED=`expr $GR_TRANSLATED + $TT`
+				GR_UNTRANSLATED=`expr $GR_UNTRANSLATED + $TU`
+				GR_FUZZY=`expr $GR_FUZZY + $TF`
       			
-			#dont show completely translated files:
-      			if [ "$U" = "0" -a "$F" = "0" ]; then
-         			OK="  $path/$lang.po $T"t" [$LASTT]\n$OK"
-				echo -n
-			else
-      				echo "  $SIGNS$path/$lang.po: $T"t"$F"f"$U"u" [$LASTT]" >> $TARGET_DIR/$lang.txt
-      			fi
+				#dont show completely translated files:
+      				if [ "$U" = "0" -a "$F" = "0" ]; then
+         				OK="  $path/$lang.po $T"t" [$LASTT]\n$OK"
+					echo -n
+				else
+      					echo "  $SIGNS$path/$lang.po: $T"t"$F"f"$U"u" [$LASTT]" >> $TARGET_DIR/$lang.txt
+      				fi
 			
 			
-			#copy (updated) files so that they can be translated:
-			test -d $TARGET_DIR/files/$lang/ || mkdir $TARGET_DIR/files/$lang/
-			cp $WD/material/packages.unstable$LEVEL/$path/$lang.po $TARGET_DIR/files/$lang/${path//'\/'/'_'}"_$lang.po" 
+				#copy (updated) files so that they can be translated:
+				# Only do it for unstable
+				if [ -z "$ext" ] ; then
+					test -d $TARGET_DIR/files/$lang/ || mkdir $TARGET_DIR/files/$lang/
+					cp $WD/material/packages.$dist$LEVEL/$path/$lang.po $TARGET_DIR/files/$lang/${path//'\/'/'_'}"_$lang.po"
+				fi
 
-			mv $WD/material/packages.unstable$LEVEL/$path/$lang.po.orig $WD/material/packages.unstable$LEVEL/$path/$lang.po >/dev/null 2>&1
-    		else #=if not existing
-			MISSING_U=`untranslated $WD/material/packages.unstable$LEVEL/$path/*.pot`
-			test -z $MISSING_U && MISSING_U=0
-      			MISSING="$MISSING  $path/$lang.po "$MISSING_U"u\n"
-      			#echo "  !!$path/$lang.po"
-    		fi
+				mv $WD/material/packages.$dist$LEVEL/$path/$lang.po.orig $WD/material/packages.$dist$LEVEL/$path/$lang.po >/dev/null 2>&1
+    			else #=if not existing
+				MISSING_U=`untranslated $WD/material/packages.$dist$LEVEL/$path/*.pot`
+				test -z $MISSING_U && MISSING_U=0
+      				MISSING="$MISSING  $path/$lang.po "$MISSING_U"u\n"
+      				#echo "  !!$path/$lang.po"
+    			fi
 
-    		if [ -e $WD/material/packages.testing$LEVEL/$path/$lang.po ]; then #if the file does exist
-      			LASTT_T=`translator $WD/material/packages.testing$LEVEL/$path/$lang.po`
-
-			$GETTEXT/msgmerge -U $WD/material/packages.testing$LEVEL/$path/$lang.po $WD/material/packages.testing$LEVEL/$path/*.pot > /dev/null 2>&1
-
-                        $GETTEXT/msgfmt $WD/material/packages.testing$LEVEL/$path/$lang.po > /dev/null 2>&1|| (echo "$path/$lang.po [$LASTT_T]" >> $TARGET_DIR/$lang.testing.txt; touch /tmp/.$LEVEL.error; return 1) || continue
-
-			#strings of this package:
-      			U_T=`untranslated $WD/material/packages.testing$LEVEL/$path/$lang.po`
-      			F_T=`fuzzy $WD/material/packages.testing$LEVEL/$path/$lang.po`
-     			T_T=`translated $WD/material/packages.testing$LEVEL/$path/$lang.po` 
-      			test -z "$U_T" && U_T=0
-      			test -z "$F_T" && F_T=0
-      			test -z "$T_T" && T_T=0
-			
-      			#get infos:
-			TU_T=`expr $TU_T + $U_T`
-      			TT_T=`expr $TT_T + $T_T`
-      			TF_T=`expr $TF_T + $F_T`
-
-      			
-			#dont show completely translated files:
-      			if [ "$U_T" = "0" -a "$F_T" = "0" ]; then
-         			OK_T="  $path/$lang.po $T_T"t" [$LASTT_T]\n$OK_T"
-				echo -n
-			else
-      				echo "  $path/$lang.po: $T_T"t"$F_T"f"$U_T"u" [$LASTT_T]" >> $TARGET_DIR/$lang.testing.txt
-      			fi
-			
-    		else #=if not existing
-			MISSING_U_T=`untranslated $WD/material/packages.testing$LEVEL/$path/*.pot`
-			test -z $MISSING_U_T && MISSING_U_T=0
-      			MISSING_T="$MISSING_T  $path/$lang.po "$MISSING_U_T"u\n"
-      			#echo "  !!$path/$lang.po"
-    		fi
-	done #for path in `cat paths`; do
+		done #for path in `cat paths`; do
  
- 	echo -e "\nTranslated:" >> $TARGET_DIR/$lang.txt
-	echo -e "$OK" >> $TARGET_DIR/$lang.txt
-	OK=""
- 	echo -e "\nTranslated:" >> $TARGET_DIR/$lang.testing.txt
-	echo -e "$OK_T" >> $TARGET_DIR/$lang.testing.txt
-	OK_T=""
+	 	echo -e "\nTranslated:" >> $TARGET_DIR/$lang.$ext.txt
+		echo -e "$OK" >> $TARGET_DIR/$lang.ext.txt
+		OK=""
 
-  	echo -e "Missing files:\n$MISSING\n" >>  $TARGET_DIR/$lang.txt
-  	echo -e "Missing files:\n$MISSING_T\n" >>  $TARGET_DIR/$lang.testing.txt
-	if [ "$TOTALU" != 0 ] ; then
-		P=`echo "$TT * 100 / $TOTALU"|bc`
-	else
+  		echo -e "Missing files:\n$MISSING\n" >>  $TARGET_DIR/$lang$ext.txt
+		if [ "$TOTALU" != 0 ] ; then
+			P=`echo "$TT * 100 / $TOTALU"|bc`
+		else
 		P=0
-	fi
-  	STR=`echo "$TT + $TU + $TF" | bc`	
-	if [ "$TOTALU_T" != 0 ] ; then
-		P_T=`echo "$TT_T * 100 / $TOTALU_T"|bc`
-	else
-		P_T=0
-	fi
-  	STR_T=`echo "$TT_T + $TU_T + $TF_T" | bc`
-  	echo -e "Global statistics: "$TT"t"$TF"f"$TU"u ($P%)     (total strings: $TOTALU=100%)\n(From all $lang.po files)" >> $TARGET_DIR/$lang.txt
-  	echo -e "Global statistics: "$TT_T"t"$TF_T"f"$TU_T"u ($P_T%)     (total strings: $TOTALU_T=100%)\n(From all $lang.po files)" >> $TARGET_DIR/$lang.testing.txt
-  	if [ "$STR" -gt "$TOTALU" ]; then
-  		echo "  You have more strings translated/fuzzy/untranslated that in
-  the pot-templates. Please check about that!" >>  $TARGET_DIR/$lang.txt
-  	fi
-  	if [ "$STR_T" -gt "$TOTALU_T" ]; then
-  		echo "  You have more strings translated/fuzzy/untranslated that in
-  the pot-templates. Please check about that!" >>  $TARGET_DIR/$lang.testing.txt
-  	fi
-  	test -e /tmp/.$LEVEL.error && echo -e "SOME FILE(S) ARE CORRUPTED! Those are marked with \"!\".\n Run a \"msgfmt --check <po-file> to see what's wrong!\"" >>  $TARGET_DIR/$lang.txt
-  	echo >>  $TARGET_DIR/$lang.testing.txt
+		fi
+	  	STR=`echo "$TT + $TU + $TF" | bc`	
+	  	echo -e "Global statistics: "$TT"t"$TF"f"$TU"u ($P%)     (total strings: $TOTALU=100%)\n(From all $lang.po files)" >> $TARGET_DIR/$lang$ext.txt
+	  	if [ "$STR" -gt "$TOTALU" ]; then
+  			echo "  You have more strings translated/fuzzy/untranslated that in
+  the pot-templates. Please check about that!" >>  $TARGET_DIR/$lang$ext.txt
+	  	fi
+	  	test -e /tmp/.$LEVEL.error && echo -e "SOME FILE(S) ARE CORRUPTED! Those are marked with \"!\".\n Run a \"msgfmt --check <po-file> to see what's wrong!\"" >>  $TARGET_DIR/$lang$ext.txt
+	done # for dist in...
+	
+	# Special info about the master file, for unstable only
 	if [ $LEVEL = 1 ]; then
 		if [ -f $WD/material/packages.unstable1/debian-installer/packages/po/$lang.po ]; then
 			MASTER_F=`fuzzy $WD/material/packages.unstable1/debian-installer/packages/po/$lang.po`
@@ -511,6 +443,7 @@ for lang in `cat $WD/config/languages`; do #run for every language
 
 	fi
 
+	# Add spellcheck info to the unstable files
 	SPELLCHECK=`grep "$lang" $WD/material/spellcheck${LEVEL}.txt | sed "s/$lang //g"`
 	if [ "$SPELLCHECK" != "" ]; then
 		printf  "Spellcheck:
@@ -522,8 +455,6 @@ for lang in `cat $WD/config/languages`; do #run for every language
 	else
 		echo "No spellcheck available for $NAME."  >>  $TARGET_DIR/$lang.txt
 	fi
-	echo >>  $TARGET_DIR/$lang.txt
-	echo >>  $TARGET_DIR/$lang.testing.txt
 
   	print_text
 
