Report error if /target/etc/apt/sources.list is missing.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@1919 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/rootskel/src/bin/apt-update b/rootskel/src/bin/apt-update
--- a/rootskel/src/bin/apt-update
+++ b/rootskel/src/bin/apt-update
@@ -1,5 +1,10 @@
 #!/bin/sh -e
 
+if [ ! -f /target/etc/apt/sources.list ] ; then
+    echo "apt-update: error: Missing /target/etc/apt/sources.list."
+    exit 1
+fi
+
 PATH=$PATH:/target/usr/bin:/target/bin:/target/usr/sbin:/target/sbin \
 LD_LIBRARY_PATH=/usr/lib:/lib:/target/usr/lib:/target/lib \
 /target/usr/bin/apt-get \
