many fixes and enhancements only do the long scan after prompting the user
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@4778 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/iso-scan/debian/postinst b/tools/iso-scan/debian/postinst
--- a/tools/iso-scan/debian/postinst
+++ b/tools/iso-scan/debian/postinst
@@ -5,6 +5,7 @@ set -e
 ISO_COUNT=0
 ISO_MOUNT_COUNT=0
 MOUNTABLE_DEVS_COUNT=0
+TOPLEVEL_DIRS_COUNT=0
 
 log () {
     logger -t hd-image-detect "$@"
@@ -20,7 +21,10 @@ block_devices () {
 }
 
 mount_device () {
-	mount -t auto -o ro $1 /hd-media 2>/dev/null
+	dev_to_mount=$1
+	db_subst iso-scan/progress_mount DRIVE $dev_to_mount
+	db_progress INFO iso-scan/progress_mount
+	mount -t auto -o ro $dev_to_mount /hd-media 2>/dev/null
 }
 		
 is_debian_iso () {
@@ -74,7 +78,7 @@ for dev in $DEVS; do
 done
 
 log "Searching for Debian installation media..."
-db_progress START 0 $(expr $DEV_COUNT \* 2) iso-scan/progress_title
+db_progress START 0 $DEV_COUNT iso-scan/progress_title
 
 # Load up every filesystem known to man. The drive could have anything.
 FS="ext2 ext3 reiserfs fat vfat xfs iso9660"
@@ -85,21 +89,31 @@ done
 mkdir /cdrom 2>/dev/null || true
 mkdir /hd-media 2>/dev/null || true
 
-log "First pass: Look for *.iso in top-level of each filesystem."
+log "First pass: Look for ISOs near top-level of each filesystem."
 for dev in $DEVS; do
-	db_subst iso-scan/progress_pass1 DRIVE $dev
-	db_progress INFO iso-scan/progress_pass1
 	if mount_device $dev; then
+		db_subst iso-scan/progress_scan DRIVE $dev
 		log "Mounted $dev for first pass"
 		MOUNTABLE_DEVS="$MOUNTABLE_DEVS $dev"
 		MOUNTABLE_DEVS_COUNT=$(expr $MOUNTABLE_DEVS_COUNT + 1)
-		for iso in /hd-media/*.iso /hd-media/*.ISO; do
-			if [ -e $iso ]; then
-				log "Found ISO $iso on $dev"
-				ISO_COUNT=$(expr $ISO_COUNT + 1)
-				try_iso $iso
+		cd /hd-media
+		for dir in . *; do
+			if [ -d "$dir" ]; then
+				if [ "$dir" != "." ]; then 
+					TOPLEVEL_DIRS_COUNT=$(expr $TOPLEVEL_DIRS_COUNT + 1)
+				fi
+				db_subst iso-scan/progress_scan DIRECTORY "$dir/"
+				db_progress INFO iso-scan/progress_scan
+				for iso in $dir/*.iso $dir/*.ISO; do
+					if [ -e $iso ]; then
+						log "Found ISO $iso on $dev"
+						ISO_COUNT=$(expr $ISO_COUNT + 1)
+						try_iso $iso
+					fi
+				done
 			fi
 		done
+		cd /
 		umount /hd-media
 	fi
 
@@ -111,47 +125,64 @@ for dev in $DEVS; do
 	db_progress STEP 1
 done
 
-log "Second pass: Search whole filesystems for isos."
-# To save time, only ones we mounted successfully before.
-for dev in $MOUNTABLE_DEVS; do
-	db_subst iso-scan/progress_pass2 DRIVE $dev
-	db_progress INFO iso-scan/progress_pass2
-	db_subst iso-scan/progress_pass2_dir DRIVE $dev
-	if mount_device $dev; then
-		log "Mounted $dev for second pass"
-		for toplevel in /hd-media/*; do
-			# Make the progess at least show top level dirs.
-			# Showing all dirs would probably be too much
-			# overhead.
-			db_subst iso-scan/progress_pass2_dir DIRECTORY $toplevel
-			db_progress INFO iso-scan/progress_pass2_dir
-			for iso in $(find /hd-media/$toplevel 2>/dev/null | grep -i '\.iso$'); do
-				log "Found ISO $iso on $dev"
-				ISO_COUNT=$(expr $ISO_COUNT + 1)
-				try_iso $iso
-			done
-		done
-		umount /hd-media
-	fi
-
-	db_progress STEP 1
-done
-
 db_progress STOP
+
+if [ "$MOUNTABLE_DEVS_COUNT" != 0 ]; then
+	# Ask about the more expensive second pass.
+	db_fset iso-scan/ask_second_pass seen false
+	db_subst iso-scan/ask_second_pass NUM_FILESYSTEMS $MOUNTABLE_DEVS_COUNT
+	db_subst iso-scan/ask_second_pass NUM_DIRS $TOPLEVEL_DIRS_COUNT
+	db_input critical iso-scan/ask_second_pass || true
+	db_go || true
+
+	db_get iso-scan/ask_second_pass
+	if [ "$RET" = true ]; then
+		db_progress START 0 $TOPLEVEL_DIRS_COUNT iso-scan/progress_title
+		log "Second pass: Search whole filesystems for ISOs."
+		# To save time, only ones we mounted successfully before.
+		for dev in $MOUNTABLE_DEVS; do
+			if mount_device $dev; then
+				db_subst iso-scan/progress_scan DRIVE $dev
+				log "Mounted $dev for second pass"
+				cd /hd-media
+				for dir in *; do
+					if [ -d "$dir" ]; then
+						db_subst iso-scan/progress_scan DIRECTORY "$dir/"
+						db_progress INFO iso-scan/progress_scan
+						for iso in $(find $dir 2>/dev/null | grep -i '\.iso$'); do
+							log "Found ISO $iso on $dev"
+							ISO_COUNT=$(expr $ISO_COUNT + 1)
+							try_iso $iso
+						done
+						db_progress STEP 1
+					fi
+				done
+				cd /
+				umount /hd-media
+			fi
+
+		done
+
+		db_progress STOP
+	fi
+fi
 
 # Failure. Display the best message we can about what happened.
 # TODO manual filename entry
+# Let them know the second pass failed too.
 if [ "$ISO_COUNT" = 0 ]; then
+	db_fset iso-scan/no-isos seen false
 	db_subst iso-scan/no-isos NUM_FILESYSTEMS $MOUNTABLE_DEVS_COUNT
 	db_input critical iso-scan/no-isos || true
 elif [ "$ISO_MOUNT_COUNT" != "$ISO_COUNT" ]; then
-	db_subst iso-scan/corrupt-isos ISO_COUNT $ISO_COUNT
-	db_subst iso-scan/corrupt-isos ISO_MOUNT_COUNT $ISO_MOUNT_COUNT
-	db_input critical iso-scan/corrupt-isos || true
-else
+	db_fset iso-scan/bad-isos seen false
 	db_subst iso-scan/bad-isos ISO_COUNT $ISO_COUNT
+	db_subst iso-scan/bad-isos ISO_MOUNT_FAILURES $(expr $ISO_COUNT - $ISO_MOUNT_COUNT)
 	db_input critical iso-scan/bad-isos || true
+else
+	db_fset iso-scan/other-isos seen false
+	db_subst iso-scan/other-isos ISO_COUNT $ISO_COUNT
+	db_input critical iso-scan/other-isos || true
 fi
 db_go || true
-log "Aborting with ISO_COUNT = $ISO_COUNT, MOUNTABLE_DEVS_COUNT = $MOUNTABLE_DEVS_COUNT, ISO_MOUNT_COUNT = $ISO_MOUNT_COUNT"
-exit 1
+log "Failing with ISO_COUNT = $ISO_COUNT, MOUNTABLE_DEVS_COUNT = $MOUNTABLE_DEVS_COUNT, ISO_MOUNT_COUNT = $ISO_MOUNT_COUNT"
