Final(?) changes for the new default entry
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@15472 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/languagechooser/languagemap b/packages/languagechooser/languagemap
--- a/packages/languagechooser/languagemap
+++ b/packages/languagechooser/languagemap
@@ -20,15 +20,17 @@ LANGUAGE=C
 
 # A colon separated priority list of language codes and locales to use
 # when selecting translations.
-LANGUAGELIST=
+LANGUAGELIST=C
 
 # The assumed country (location)
-COUNTRY=us
+COUNTRY=US
 
 # echo "Looking up '$LANGNAME'"
 
-line=`grep "^$LANGNAME" $languages`
+line=$(grep "^$LANGNAME" $languages || true)
 #echo L: $line 1>&2
+
+log "line=$line"
 
 if [ "$line" ] ; then
     OLD_IFS="$IFS"
@@ -47,6 +49,12 @@ if [ "$line" ] ; then
     if [ -z "$LANGUAGELIST" ] ; then
 	LANGUAGELIST="$LANGUAGE"
     fi
+
 else
     echo "error: Unable to locate info on language '$LANGNAME'"
+    log "error: Unable to locate info on language '$LANGNAME'"
 fi
+
+# bubulle 5/15/2004 : needed when choosing "English (C)". I've been unable to 
+# sort out why
+exit 0
