Adding reworked layout with plugin infrastructure together with Otavio.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@64175 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/debian-installer-launcher/debian-installer-launcher b/packages/debian-installer-launcher/debian-installer-launcher
--- a/packages/debian-installer-launcher/debian-installer-launcher
+++ b/packages/debian-installer-launcher/debian-installer-launcher
@@ -1,119 +1,98 @@
 #!/bin/sh
 
+# This script can launch a Debian Installer instance. It has multiple plugins
+# that must provide the following methods:
+#
+#  - <plugin>_usage
+#  - <plugin>_cleanup
+#  - <plugin>_prepare
+#  - <plugin>_run
+
 set -e
 
-DI_FRONTEND=$1
-DI_PRIORITY=$2
-
-TERMINAL=""
-
-prepare ()
+call_for_plugin()
 {
-	# Checking for x11
-	if [ -n "$DISPLAY" ]; then
-		# Checking for debconf frontend (gnome)
-		if dpkg -s libgnome2-perl > /dev/null 2>&1; then
-			export DEBIAN_FRONTEND=gnome
-		fi
-	fi
+	plugin=$1
+	method=$2
+	shift 2
 
-	# Checking for debconf frontend (terminal fallback)
-	if [ -z $DEBIAN_FRONTEND ]; then
-		TERMINAL="x-terminal-emulator -e"
-	fi
+	args="$@"
+
+	${plugin}_${method} $args
 }
 
-cleanup () {
-	# Stopping syslogd/klogd
-	# ->the sed horror could be improved (FIXME;)
-	# string: [A-Z][a-z]: [0-9] [0-9]rce [0-9]...
-	# we only want the [0-9]rce, but without the rce.
-	for PID in $(fuser -m /live/installer/var/log/syslog 2>&1 | \
-		sed "s,.*: ,,g;s, ,\n,g" | grep 'rce$' | \
-		sed -e 's/rce//g'); do
-		kill -9 $PID > /dev/null 2>&1 || true
+call_for_plugins()
+{
+	method=$1
+	shift
+
+	args="$@"
+
+	for p in $PLUGINS; do
+		call_for_plugin $p $method $args
 	done
-
-	# Unmounting installer cdrom
-	umount -f /live/installer/cdrom > /dev/null 2>&1 || true
-
-	# Unmounting pseudo filesystems
-	umount -f /live/installer/dev/pts > /dev/null 2>&1 || true
-	umount -f /live/installer/dev > /dev/null 2>&1 || true
-	umount -f /live/installer/proc > /dev/null 2>&1 || true
-	umount -f /live/installer/sys > /dev/null 2>&1 || true
-	umount -f /live/installer/tmp > /dev/null 2>&1 || true
-
-	# Remove unpacked initrd
-	rm -rf /live/installer
-	rm -f /tmp/debian-installer
 }
+
+usage()
+{
+	cat <<EOF
+Debian Installer Launcher
+
+OPTIONS:
+
+   -p, --plugin  Plugin to use
+
+$(call_for_plugins "usage")
+
+
+
+EOF
+}
+
+cleanup()
+{
+	call_for_plugins "cleanup"
+}
+
+PLUGINS_DIR="/usr/share/debian-installer-launcher/plugins"
+PLUGINS=""
+PLUGIN=""
 
 # Setup cleanup function
 trap 'cleanup' EXIT HUP INT QUIT TERM
 
-prepare
+# For easy development, override it in case we are in the source tree
+[ -x debian-installer-launcher ] && PLUGINS_DIR="plugins"
 
-if [ -z $DI_FRONTEND ] || [ -z $DI_PRIORITY ]; then
-	$TERMINAL /usr/share/debian-installer-launcher/debconf_mode.sh
-fi
-
-if [ "$DI_FRONTEND" = gtk ]; then
-	xhost +local:
-fi
-
-# Source configuration found by debconf
-. /tmp/debian-installer
-
-# Find an debian-installer initrd, preferably the gtk one
-for IMAGE in /live/image/install/gtk/initrd.gz /live/image/install/initrd.gz; do
-	[ -e $IMAGE ] && break
+# Load plugins
+for p in $PLUGINS_DIR/*; do
+	. $p
+	PLUGINS="${p#$PLUGINS_DIR/} $PLUGINS"
 done
 
-[ ! -e $IMAGE ] && echo "no suitable d-i initrd image found, aborting." && exit 1
-
-echo "Loading debian-installer..."
-
-# Create the temporary directory
-mkdir -p /live/installer
-
-# Unpack the initrd
-cd /live/installer
-zcat $IMAGE | cpio -id > /dev/null 2>&1
-
-$TERMINAL /usr/share/debian-installer-launcher/debconf_kernel.sh
-
-# Bindmount installer media
-mkdir -p /live/installer/cdrom
-mount -o bind /live/image /live/installer/cdrom
-
-# Bindmount pseudo filesytem
-mount -o bind /dev /live/installer/dev
-mount -o bind /dev/pts /live/installer/dev/pts
-mount -o bind /proc /live/installer/proc
-mount -o bind /sys /live/installer/sys
-mount -o bind /tmp /live/installer/tmp
-
-# Preseeding shutdown command
-cat >> preseed.cfg << EOF
-# Select udeb for installation to allow exiting the installer
-d-i anna/choose_modules string di-utils-exit-installer
-# Ask question regardless from that it's preseeded above
-d-i anna/choose_modules seen false
-# Skip the exit timeout
-d-i di-utils-reboot/really_reboot boolean false
-EOF
-
-# Preseeding installer export mode
-if [ "$DI_PRIORITY" = expert ]; then
-
-cat >> preseed.cfg << EOF
-# Setting expert mode
-d-i debconf/priority select low
-debconf debconf/priority select low
-EOF
-
+# Default to live plugin on live systems
+if [ -e /live/image ]; then
+	PLUGIN=live
 fi
 
-# Launching debian-installer
-/usr/share/debian-installer-launcher/debian-installer.sh
+# Handle generic launcher arguments
+for arg in $@; do
+	case "$arg" in
+		-h|--help)
+			usage
+			exit 0
+			;;
+		-p=*|--plugin=*)
+			PLUGIN=${arg#*=}
+			;;
+	esac
+done
+
+# Check for plugin
+if ! echo $PLUGINS | grep -q $PLUGIN; then
+	echo "ERROR: '$PLUGIN' is not a valid plugin. Check and try again."
+	exit 1
+fi
+
+call_for_plugin $PLUGIN "prepare" $@
+call_for_plugin $PLUGIN "run"
