* apt-install/in-target: in some cases chroot_setup would fail because of an   earlier error but leave a lock file behind which would prevent recovery.   Add some basic checks in chroot_setup and bail out if these fail.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@42201 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/debian-installer-utils/apt-install b/packages/debian-installer-utils/apt-install
--- a/packages/debian-installer-utils/apt-install
+++ b/packages/debian-installer-utils/apt-install
@@ -6,7 +6,7 @@ queue=/var/lib/apt-install/queue
 
 # If we don't have a working mirror yet, only queue the package;
 # it will be installed later by the postinst in base-installer.
-if [ ! -f /target/etc/apt/sources.list ] ; then
+if [ ! -f /target/etc/apt/sources.list ]; then
 	# Add to list of extra packages to be installed into /target/.
 	mkdir -p /var/lib/apt-install
 	touch $queue
@@ -20,7 +20,10 @@ if [ ! -f /target/etc/apt/sources.list ] ; then
 	exit 1 # Return error as the package is not ready to be used yet.
 fi
 
-chroot_setup
+if ! chroot_setup; then
+	logger -t apt-install "Unexpected error: $pkg not processed"
+	exit 1
+fi
 
 # Disable debconf questions.
 DEBIAN_FRONTEND=noninteractive
diff --git a/packages/debian-installer-utils/in-target b/packages/debian-installer-utils/in-target
--- a/packages/debian-installer-utils/in-target
+++ b/packages/debian-installer-utils/in-target
@@ -2,7 +2,10 @@
 set -e
 . /lib/chroot-setup.sh
 
-chroot_setup
+if ! chroot_setup; then
+	logger -t in-target "Unexpected error: command '$@' not executed"
+	exit 1
+fi
 
 DEBCONF_READFD=0
 export DEBCONF_READFD
