* Add the pcnet32 driver to nic-modules (used by vmware, we have space).   * Make copy-modules abort if tar fails (lost that when converting from     fifo).
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@5932 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/kernel/linux-kernel-di/copy-modules b/kernel/linux-kernel-di/copy-modules
--- a/kernel/linux-kernel-di/copy-modules
+++ b/kernel/linux-kernel-di/copy-modules
@@ -111,11 +111,20 @@ for i in $(
 
 	# copy kernel modules to package build dir
 	cd $moddir/kernel
-	tar cfT - $tmpdir/module-list/$i |
-	(
+	ret=$(((
+		set +e
+		tar cfT - $tmpdir/module-list/$i
+		printf $? >&3
+	) | (
+		set +e
 		dir=$home/debian/$i-$version-di/lib/modules/$installedname/kernel
 		mkdir -p $dir
 		cd $dir
 		tar xf -
-	)
+		printf $? >&3
+	)) 3>&1)
+	if [ "$ret" != "00" ]; then
+		echo "tar failed" >&2
+		exit $ret
+	fi
 done
