Preliminary fix of postinst.
This is not the real thing, the arcboot installation should be fixed.


git-svn-id: svn://svn.debian.org/svn/d-i/trunk@6782 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/mips/arcboot-installer/debian/arcboot-installer.postinst b/tools/mips/arcboot-installer/debian/arcboot-installer.postinst
--- a/tools/mips/arcboot-installer/debian/arcboot-installer.postinst
+++ b/tools/mips/arcboot-installer/debian/arcboot-installer.postinst
@@ -1,18 +1,7 @@
 #!/bin/sh
 set -e
 
-if apt-install arcboot ; then
-	:
-else
-	log "Calling 'apt-install arcboot' failed"
-	# What to do now?
-	db_input critical arcboot-installer/apt-install-failed || [$? -eq 30]
-	db_go
-	db_get
-	if [ true != "$RET" ] ; then
-		exit 1
-	fi
-fi
+. /usr/share/debconf/confmodule
 
 if [ -f /etc/mtab ]; then
     MTAB=/etc/mtab
@@ -21,38 +10,19 @@ else
 fi
 
 # detect which is the root partition: /target
-# ugh, I wanted to use awk, but sed has better chance of being in busybox
-rootfs=`/target/bin/sed -ne '/^[^ ]* \/target /s/ .*//p' $MTAB`
+rootfs=`grep ' /target ' $MTAB |cut -d' ' -f1 -s`
+defaultbootdev=`echo $rootfs |sed 's/part[0-9]\+$/disc/'`
+rootfs=`mapdevfs $rootfs`
+defaultbootdev=`mapdevfs $defaultbootdev`
 
-# detect which hard drive has /target/boot mounted on it. this does *not*
-# have to be the same as the drive /target is mounted on.
-defaultbootdev=`/target/bin/sed -ne '/^[^ ]* \/target\/boot /s/ .*//p' $MTAB`
-
-if [ "$defaultbootdev" = '' ]; then
-	defaultbootdev=$rootfs
-fi
-
-defaultbootdev=`/target/bin/echo $defaultbootdev | /target/bin/sed 's/part[0-9]\+$/disc/'` 
-
-if [ "$defaultbootdev" = '' ]; then
-	defaultbootdev='/dev/sda'
-fi
-
-. /usr/share/debconf/confmodule
 db_fget arcboot/boot_device seen
-[ "$RET" = true ] || db_set  arcboot/boot_device"$defaultbootdev"
+[ "$RET" = true ] || db_set arcboot/boot_device "$defaultbootdev"
 db_input high arcboot/boot_device || [ $? -eq 30 ]
 db_go || true
-
 db_get arcboot/boot_device
+
 bootdev=$RET
-
-if [ "$bootdev" = '' ]; then
-	bootdev=$defaultbootdev
-fi
-
-bootdev=`mapdevfs $bootdev`
-rootfs=`mapdevfs $rootfs`
+[ "$bootdev" != '' ] || bootdev=$defaultbootdev
 
 # Use a serial console if current default console is a serial port.
 # default console is last listed
@@ -60,7 +30,10 @@ defconsole=$(sed -e 's/.*console=/console=/' /proc/cmdline)
 if echo "${defconsole}" | grep -q console=ttyS; then
     PORT=$(echo "${defconsole}" | sed -e 's%^console=ttyS%%' -e 's%,.*%%')
     SPEED=$(echo "${defconsole}" | sed -e 's%^console=ttyS[0-9]\+,%%' -e 's% .*%%')
-    SERIAL="${PORT},${SPEED}"
+    SERIAL="${PORT}"
+    if [ "${SPEED}" != '' ]; then
+	SERIAL="${SERIAL},${SPEED}"
+    fi
 
     db_subst arcboot-installer/serial-console PORT "ttyS${PORT}"
     db_subst arcboot-installer/serial-console SPEED "${SPEED}"
@@ -68,13 +41,36 @@ if echo "${defconsole}" | grep -q console=ttyS; then
     db_go || true
 fi
 
-#write out arcboot.conf
-echo '	label=Linux' >> /target/etc/arcboot.conf
-echo 'image=/boot/vmlinuz' >> /target/etc/arcboot.conf
+# write out arcboot.conf
+(   echo 'label=Linux'
+    echo '  image=/vmlinux'
 
-if [ "${SERIAL}" ]; then
-    echo "  append=\"root=${rootfs} console=ttyS${SERIAL}\"" >> /target/etc/arcboot.conf
-else
-    echo "  append=\"root=${rootfs} " >> /target/etc/arcboot.conf
+    if [ "${SERIAL}" ]; then
+	echo "  append=\"root=${rootfs} console=ttyS${SERIAL}\""
+    else
+	echo "  append=\"root=${rootfs}\""
+    fi
+) > /target/etc/arcboot.conf
 
-chroot /target /usr/bin/arcboot $bootdev
+# Install arcboot only after arcboot.conf is created since the arcboot
+# postinst fails in a chroot.
+#
+# HACK ALERT!
+# The arcboot postinst wants to read $bootdev from debconf _in the chroot_,
+# which is still empty. We ignore the resulting apt-install error and do the
+# install ourself. If apt-install fails for a different reason, we are lost.
+set +e
+apt-install arcboot
+set -e
+chroot /target /usr/sbin/arcboot $bootdev
+
+#if ! apt-install arcboot; then
+#	log "Calling 'apt-install arcboot' failed"
+#	# What to do now?
+#	db_input critical arcboot-installer/apt-install-failed || [$? -eq 30]
+#	db_go
+#	db_get
+#	if [ true != "$RET" ] ; then
+#		exit 1
+#	fi
+#fi
