remember to apt-install arcboot
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@3112 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/mips/arcboot-installer/debian/arcboot-installer.postinst b/tools/mips/arcboot-installer/debian/arcboot-installer.postinst
--- a/tools/mips/arcboot-installer/debian/arcboot-installer.postinst
+++ b/tools/mips/arcboot-installer/debian/arcboot-installer.postinst
@@ -1,6 +1,19 @@
 #!/bin/sh
 set -e
 
+if apt-install arcboot ; then
+	:
+else
+	log "Calling 'apt-install arcboot' failed"
+	# What to do now?
+	db_input critical arcboot-installer/apt-install-failed || [$? -eq 30]
+	db_go
+	db_get
+	if [ true != "$RET" ] ; then
+		exit 1
+	fi
+fi
+
 if [ -f /etc/mtab ]; then
     MTAB=/etc/mtab
 else
