Add support for the Thecus N2100.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@39031 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/oldsys-preseed/oldsys-preseed b/packages/oldsys-preseed/oldsys-preseed
--- a/packages/oldsys-preseed/oldsys-preseed
+++ b/packages/oldsys-preseed/oldsys-preseed
@@ -65,6 +65,51 @@ case "`archdetect`" in
 			add "$FILE" "ethdetect/use_firewire_ethernet" "boolean" "false"
 		fi
 	;;
+	arm/iop3xx | armeb/iop3xx)
+		# FIXME: test for Thecus
+		if [ 1 ]; then
+			check_file /proc/mtd
+			config=$(get_mtdblock "user")
+			if [ -z "$config" ]; then
+				log "Can't find MTD partition holding config data"
+				exit
+			fi
+			path=/tmp/oldsys-preseed
+			mkdir -p $path/mnt $path/defaults
+			mount -t jffs2 /dev/$config $path/mnt
+			if [ -e $path/mnt/default.tar.gz ]; then
+				(cd $path/defaults && tar -xzf $path/mnt/default.tar.gz)
+				if [ -e $path/defaults/app/etc/HOSTNAME ]; then
+					DEFAULT_HOSTNAME=$(cut -d . -f 1 $path/defaults/app/etc/HOSTNAME)
+					DEFAULT_DOMAIN=$(cut -d . -f 2- $path/defaults/app/etc/HOSTNAME)
+				fi
+				if [ -e $path/defaults/app/cfg/cfg_nic0 ]; then
+					parse_ifconfig $path/defaults/app/cfg/cfg_nic0
+					[ -n "$IPADDRESS" ] && DEFAULT_IPADDRESS=$IPADDRESS
+					unset IPADDRESS NETMASK GATEWAY
+				fi
+			fi
+			parse_unix_tree $path/mnt
+			NET_CONFIG=static
+			parse_ifconfig $path/mnt/cfg/cfg_nic0
+			# Use DHCP if the original IP from the firmware has never been changed.
+			# The default IP address 192.168.1.100 but defaults/app/cfg/cfg_nic0
+			# could theoretically contain a different value so take both into account.
+			# Set the fallback to 192.168.1.100 so a fixed value can be documented.
+			if [ "$IPADDRESS" = "$DEFAULT_IPADDRESS" -o "$IPADDRESS" = "192.168.1.100" ]; then
+				unset NET_CONFIG
+				IPADDRESS=192.168.1.100
+				unset NETMASK GATEWAY
+			fi
+			HOSTNAME=$(cut -d . -f 1 $path/mnt/etc/HOSTNAME)
+			DOMAIN=$(cut -d . -f 2- $path/mnt/etc/HOSTNAME)
+			unset_matching_var "$HOSTNAME" "$DEFAULT_HOSTNAME"
+			unset_matching_var "$DOMAIN" "$DEFAULT_DOMAIN"
+			umount $path/mnt
+			rm -rf $path/defaults
+			rmdir $path/mnt $path || true
+		fi
+	;;
 	mipsel/bcm947xx)
 		# Some BCM947xx devices use NVRAM to store their Linux
 		# configuration, some use a Linux filesystem.  We only
