Add support for the D-Link DNS-323, thanks to a patch from Matt Palmer.  Closes: #502821.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@57778 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/oldsys-preseed/oldsys-preseed b/packages/oldsys-preseed/oldsys-preseed
--- a/packages/oldsys-preseed/oldsys-preseed
+++ b/packages/oldsys-preseed/oldsys-preseed
@@ -156,6 +156,27 @@ case "`archdetect`" in
 			fi
 			umount $path/rootfs || true
 			rmdir $path/rootfs $path || true
+		elif echo "$machine" | grep -q "^D-Link DNS-323"; then
+			check_file /proc/mtd
+			rootfs=$(get_mtdblock "MTD1")
+			if [ -z "$rootfs" ]; then
+				log "Can't find rootfs MTD partition"
+				exit 0
+			fi
+			INTERFACE=eth0
+			path=/tmp/oldsys-preseed
+			mkdir -p $path/rootfs
+			mount -t minix -o ro /dev/$rootfs $path/rootfs
+			parse_sib_conf $path/rootfs/sib.conf
+			umount $path/rootfs
+			rmdir $path/rootfs $path || true
+			sanity_check_static_config
+			if [ "$NET_CONFIG" != "static" ]; then
+				IPADDRESS=192.168.0.32
+				NETMASK=255.255.255.0
+				GATEWAY=192.168.0.1
+				[ -z "$NAMESERVERS" ] && NAMESERVERS=192.168.0.1
+			fi
 		elif echo "$machine" | grep -q "^HP Media Vault mv2120"; then
 			path=/tmp/oldsys-preseed
 			mkdir -p $path/sda5
