- Reduce number of error messages and use syslog instead - Improve error handling
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@41541 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/partman/partman-auto-raid/auto-raidcfg b/packages/partman/partman-auto-raid/auto-raidcfg
--- a/packages/partman/partman-auto-raid/auto-raidcfg
+++ b/packages/partman/partman-auto-raid/auto-raidcfg
@@ -11,7 +11,7 @@ create_raid() {
 	if [ "$DEV_COUNT" -lt 3 ] && [ $RAID_TYPE = "5" ] ; then
 		db_input critical partman-auto-raid/notenoughparts
 		db_go partman-auto-raid/notenoughparts
-		exit 1
+		exit 9
 	fi
 
 	SPARE_COUNT="$3"
@@ -65,16 +65,20 @@ create_raid() {
 
 	echo "Raid devices count: $DEV_COUNT"
 	if [ "$RAID_TYPE" != "0" ]; then
-		echo "Selected spare count: $NAMED_SPARES"
-		echo "Spare devices count: $SPARE_COUNT"
+		logger -t partman-auto-raid "Selected spare count: $NAMED_SPARES"
+		logger -t partman-auto-raid "Spare devices count: $SPARE_COUNT"
 		MDADM_PARAMS="-x $SPARE_COUNT $RAID_DEVICES $MISSING_DEVICES $SPARE_DEVICES $MISSING_SPARES"
 	else 
 		MDADM_PARAMS="$RAID_DEVICES"
 	fi
 
-	log-output -t partman-auto-raid \
+	if ! log-output -t partman-auto-raid \
 		mdadm --create /dev/md/$MD_NUM --auto=yes --force -R -l raid$RAID_TYPE \
 		      -n $DEV_COUNT $MDADM_PARAMS
+	then
+		logger -t partman-auto-raid "Error creating array /dev/md/$MD_NUM"
+		exit 1
+	fi
 }
 
 # Try to load the necesarry modules.
@@ -89,10 +93,10 @@ mkdir -p /dev/md
 
 # Make sure that we have md-support
 if [ ! -e /proc/mdstat ]; then
-	db_set partman-auto-raid/nomd false
-	db_input critical partman-auto-raid/nomd
+	db_set mdcfg/nomd false
+	db_input critical mdcfg/nomd
 	db_go
-	exit 1
+	exit 9
 fi
 
 # Force mdadm to be installed on the target system
@@ -101,9 +105,7 @@ apt-install mdadm || true
 # Check we have recipe(s)
 db_get partman-auto-raid/recipe
 if [ -z "$RET" ]; then
-	db_set partman-auto-raid/norecipe false
-	db_input high partman-auto-raid/norecipe
-	db_go
+	logger -t partman-auto-raid "Error: recipe missing in partman-auto-raid/recipe"
 	exit 1
 fi
 
diff --git a/packages/partman/partman-auto-raid/init.d/initial_auto_raid_fs b/packages/partman/partman-auto-raid/init.d/initial_auto_raid_fs
--- a/packages/partman/partman-auto-raid/init.d/initial_auto_raid_fs
+++ b/packages/partman/partman-auto-raid/init.d/initial_auto_raid_fs
@@ -10,15 +10,23 @@ fix_raid_fs() {
 	mountpoint=$3
 
 	dev="/var/lib/partman/devices/=dev=md=$raidnum"
-	cd $dev
-	id=$(ls -d 0-*)
-	if [ -z $id ]; then
-		db_set partman-auto-raid/nodir false
-		db_input high partman-auto-raid/nodir
+	if [ ! -d $dev ]; then
+		logger -t partman-auto-raid "Error: directory for /dev/md/$raidnum not found"
+		db_set partman-auto-raid/error false
+		db_input critical partman-auto-raid/error
 		db_go
 		exit 1
 	fi
+	cd $dev
 
+	id=$(ls -d 0-*)
+	if [ -z $id ]; then
+		logger -t partman-auto-raid "Error: incorrect directory for /dev/md/$raidnum"
+		db_set partman-auto-raid/error false
+		db_input critical partman-auto-raid/error
+		db_go
+		exit 1
+	fi
 	cd $id
 
 	if [ "$fstype" = swap ]; then
@@ -46,23 +54,16 @@ rm /var/lib/partman/do_initial_auto_raid_fs
 # Check we have the stashed value of the first RAID dev we created
 db_get partman-auto-raid/raidnum
 if [ -z "$RET" ]; then
-	db_set partman-auto-raid/noraidnum false
-	db_input high partman-auto-raid/noraidnum
+	logger -t partman-auto-raid "Error: cannot determine device number for RAID device"
+	db_set partman-auto-raid/error false
+	db_input critical partman-auto-raid/error
 	db_go
 	exit 1
 fi
-
 raidnum=$RET
 
-# Check we have recipe(s)
+# We've already checked that there is a recipe
 db_get partman-auto-raid/recipe
-if [ -z "$RET" ]; then
-	db_set partman-auto-raid/norecipe false
-	db_input high partman-auto-raid/norecipe
-	db_go
-	exit 1
-fi
-
 recipes=$RET
 
 # Try to act on each recipe we were given
