Add hooks to make it easier to change which partition table to use.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@2003 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/autopartkit/debian/postinst b/tools/autopartkit/debian/postinst
--- a/tools/autopartkit/debian/postinst
+++ b/tools/autopartkit/debian/postinst
@@ -1,6 +1,26 @@
 #! /bin/sh -e
 
-if autopartkit ; then
+. /usr/share/debconf/confmodule
+
+run_parts() {
+    partsdir="$1"
+
+    for script in "$partsdir"/*; do
+	if [ -x "$script" ] ; then
+	    "$script" || true
+	else
+	    echo "error: Unable to execute $script" 1>&2
+	fi
+    done
+}
+
+# Run all scripts to choose table file
+run_parts /usr/lib/autopartkit.d
+
+db_get autopartkit/partition_table
+table="$RET"
+
+if autopartkit "$table" ; then
     :
 else
     # This should use debconf to report the error.
