Redirect some messages from postinst into /var/log/messages.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@3708 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/autopartkit/debian/postinst b/tools/autopartkit/debian/postinst
--- a/tools/autopartkit/debian/postinst
+++ b/tools/autopartkit/debian/postinst
@@ -1,5 +1,6 @@
 #! /bin/sh -e
 
+log=/var/log/messages
 template=autopartkit/partition_table
 
 run_parts() {
@@ -14,8 +15,8 @@ run_parts() {
     done
 }
 # Try to load LVM support
-depmod -a || true
-modprobe lvm-mod || true
+depmod -a >> $log 2>&1 || true
+modprobe lvm-mod >> $log 2>&1 || true
 
 # Make sure it is installed into /target/ as well
 apt-install lvm10 || true
@@ -27,9 +28,7 @@ if autopartkit "$template" ; then
     :
 else
     # This should use debconf to report the error.
-    echo "error: autopartkit failed."
-    # No sleep in d-i environment [2002-08-21]
-    #sleep 10
+    echo "error: autopartkit failed." >> $log
     exit 1
 fi
 
