In S60frontend only allow the gtk frontend if framebuffer is available and the system has sufficient memory (for now: 92 MiB)
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@32011 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/rootskel/src/lib/debian-installer.d/S60frontend b/packages/rootskel/src/lib/debian-installer.d/S60frontend
--- a/packages/rootskel/src/lib/debian-installer.d/S60frontend
+++ b/packages/rootskel/src/lib/debian-installer.d/S60frontend
@@ -1,6 +1,33 @@
+get_mem () {
+	ram=$(grep ^MemTotal: /proc/meminfo | { read x y z; echo $y; }) || true # in kilobytes
+	if [ "$ram" = "" ]; then
+		echo "Cannot determine system memory" >&2
+        	ram=0
+	else
+	        ram=$(expr "$ram" / 1024) # convert to megabytes
+	fi
+	echo $ram
+}
+
+check_gtk () {
+	if [ -z "$TERM_FRAMEBUFFER" ] ; then
+		echo "Framebuffer not available; disabling graphical frontend" >&2
+		return 1
+	fi
+	# 88MB = 92MiB
+	if [ $(get_mem) -lt 88 ] ; then
+		echo "Insufficient memory for graphical frontend; disabling" >&2
+		return 1
+	fi
+	return 0
+}
+
 if [ -z "$DEBIAN_FRONTEND" ] ; then
 	for frontend in gtk newt slang text ; do
 		if [ -e "/usr/lib/cdebconf/frontend/$frontend.so" ]; then
+			if [ "$frontend" = gtk ] ; then
+				check_gtk || continue
+			fi
 			DEBIAN_FRONTEND=$frontend
 			break
 		fi
