Fix path to script and add extra checks
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@33054 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/g-i/FreeSans-strip b/scripts/g-i/FreeSans-strip
--- a/scripts/g-i/FreeSans-strip
+++ b/scripts/g-i/FreeSans-strip
@@ -1,6 +1,17 @@
 #! /bin/bash
 
-strip=/home/fjp/projects/d-i/scripts/g-i/strip_glyphs.pe
+exepath=$(dirname $0)
+strip=$exepath/strip_glyphs.pe
+
+if [ $# -ne 2 ] ; then
+	echo "Usage: $(basename $0) fontfile_in fontfile_out"
+	exit 0
+fi
+
+if [ ! -x "$strip" ] ; then
+	echo "Script not found: $strip"
+	exit 1
+fi
 
 if [ ! -f "$1" ] ; then
 	echo "File does not exist: $1"
