add TEST_HOSTNAME
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@45924 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/digress/test_2/web-server b/scripts/digress/test_2/web-server
--- a/scripts/digress/test_2/web-server
+++ b/scripts/digress/test_2/web-server
@@ -1,8 +1,13 @@
 #!/bin/sh
 tmp=$(tempfile)
 
-if ! wget http://$MACHINE/ -O - > /dev/null; then
-	echo "wget http://$MACHINE/ failed" >&2
+HOST="$MACHINE"
+if [ -n "$TEST_HOSTNAME" ]; then
+	HOST="$TEST_HOSTNAME"
+fi
+
+if ! wget "http://$HOST/" -O - > /dev/null; then
+	echo "wget http://$HOST/ failed" >&2
 	exit 1
 fi
 echo "Web server: ok"
