Try to use /target/bin/run-parts to execute the fragments in /usr/lib/prebaseconfig.d/.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@1174 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/prebaseconfig/debian/postinst b/tools/prebaseconfig/debian/postinst
--- a/tools/prebaseconfig/debian/postinst
+++ b/tools/prebaseconfig/debian/postinst
@@ -112,15 +112,19 @@ cp /usr/share/prebaseconfig/inittab /target/etc/inittab
 eject || /target/usr/bin/eject || true
 
 # run-parts is part of debianutils, is it available in d-i? [pere 2002-11-02]
-#run-parts --report /usr/lib/prebaseconfig.d || true
-# Using this until run-parts is available.
-for f in /usr/lib/prebaseconfig.d/*; do
-    if [ -x $f ] ; then
-	$f || true
-    else
-	echo "error: Unable to execute $f" 1>&2
-    fi
-done
+if /target/bin/run-parts --report /usr/lib/prebaseconfig.d ; then
+    :
+else
+    echo "error: run-parts failed.  Using shell script loop instead." 1>&2
+    # Using this until run-parts is available.
+    for f in /usr/lib/prebaseconfig.d/*; do
+        if [ -x $f ] ; then
+            $f || true
+        else
+            echo "error: Unable to execute $f" 1>&2
+        fi
+    done
+fi
 
 umount -a || true
 
