Do not use /target/bin/run-parts, as one of the parts will umount /target/.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@1761 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/prebaseconfig/debian/postinst b/tools/prebaseconfig/debian/postinst
--- a/tools/prebaseconfig/debian/postinst
+++ b/tools/prebaseconfig/debian/postinst
@@ -1,21 +1,16 @@
 #! /bin/sh -e
 
+# Use this instead of /target/bin/run-parts because one of the
+# parts will unmount /target/
 run_parts() {
     partsdir="$1"
-    # run-parts is part of debianutils, is it available in d-i? [pere 2002-11-02]
-    if /target/bin/run-parts --report "$partsdir" ; then
-	:
-    else
-	echo "error: run-parts failed.  Using shell script loop instead." 1>&2
-        # Using this until run-parts is available.
-	for script in "$partsdir"/*; do
-	    if [ -x "$script" ] ; then
-		"$script" || true
-	    else
-		echo "error: Unable to execute $script" 1>&2
-	    fi
-	done
-    fi
+    for script in "$partsdir"/*; do
+        if [ -x "$script" ] ; then
+            "$script" || true
+        else
+            echo "error: Unable to execute $script" 1>&2
+        fi
+    done
 }
 
 run_parts /usr/lib/prebaseconfig.d
