Redirect stderr to /var/log/messages when running prebaseconfig scripts (closes: #179240).
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@1896 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/prebaseconfig/debian/postinst b/tools/prebaseconfig/debian/postinst
--- a/tools/prebaseconfig/debian/postinst
+++ b/tools/prebaseconfig/debian/postinst
@@ -6,11 +6,12 @@ run_parts() {
     partsdir="$1"
     for script in "$partsdir"/*; do
         if [ -x "$script" ] ; then
+            echo "prebaseconfig: info: Running $script" 1>&2
             "$script" || true
         else
-            echo "error: Unable to execute $script" 1>&2
+            echo "prebaseconfig: error: Unable to execute $script" 1>&2
         fi
     done
 }
 
-run_parts /usr/lib/prebaseconfig.d
+run_parts /usr/lib/prebaseconfig.d 2>> /var/log/messages
