Report error code value when prebaseconfig script fails.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@2135 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/prebaseconfig/debian/postinst b/tools/prebaseconfig/debian/postinst
--- a/tools/prebaseconfig/debian/postinst
+++ b/tools/prebaseconfig/debian/postinst
@@ -10,7 +10,7 @@ run_parts() {
             if "$script" ; then
 		:
 	    else
-		echo "prebaseconfig: warning: $script returned error code" 1>&2
+		echo "prebaseconfig: warning: $script returned error code $?" 1>&2
 	    fi
         else
             echo "prebaseconfig: error: Unable to execute $script" 1>&2
