Report when a prebaseconfig script returns an error.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@1898 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/prebaseconfig/debian/postinst b/tools/prebaseconfig/debian/postinst
--- a/tools/prebaseconfig/debian/postinst
+++ b/tools/prebaseconfig/debian/postinst
@@ -7,7 +7,11 @@ run_parts() {
     for script in "$partsdir"/*; do
         if [ -x "$script" ] ; then
             echo "prebaseconfig: info: Running $script" 1>&2
-            "$script" || true
+            if "$script" ; then
+		:
+	    else
+		echo "prebaseconfig: warning: $script returned error code" 1>&2
+	    fi
         else
             echo "prebaseconfig: error: Unable to execute $script" 1>&2
         fi
