[project @ Arch-1:colin.watson@canonical.com--2005%kickseed--mainline--0--patch-123] add support for ks=nfs:<server>:/<path>
Original author: Colin Watson <colin.watson@canonical.com>
Date: 2005-03-01 13:41:33+00:00

git-svn-id: svn://svn.debian.org/svn/d-i/trunk@47414 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/kickseed/initrd-kickseed b/packages/kickseed/initrd-kickseed
--- a/packages/kickseed/initrd-kickseed
+++ b/packages/kickseed/initrd-kickseed
@@ -63,6 +63,18 @@ case $KS in
 			exit 1
 		fi
 		;;
+	nfs:*:/*)
+		logger -t kickseed "Retrieving kickstart file from $KS"
+		file="${KS#nfs:}"
+		server="${file%%:*}"
+		file="${file#*:}"
+		if ! mount -t nfs -o ro "$server:${file%/*}" "${KSCFG%/*}"; then
+			logger -t kickseed "... failed"
+			exit 1
+		fi
+		trap "umount '${KSCFG%/*}' || true" \
+			EXIT HUP INT QUIT TERM
+		;;
 esac
 
 case $KSCFG in
