[project @ Arch-1:colin.watson@canonical.com--2005%kickseed--mainline--0--patch-95] merge file-kickseed into initrd-kickseed Merge file-kickseed into initrd-kickseed. If reading a Kickstart file from CD-ROM, configure cdrom-detect (if installed) using udpkg to arrange for /cdrom to be accessible.
Original author: Colin Watson <colin.watson@canonical.com>
Date: 2005-02-25 14:17:55+00:00

git-svn-id: svn://svn.debian.org/svn/d-i/trunk@47387 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/kickseed/initrd-kickseed b/packages/kickseed/initrd-kickseed
--- a/packages/kickseed/initrd-kickseed
+++ b/packages/kickseed/initrd-kickseed
@@ -40,7 +40,22 @@ KS="$(kickseed_cmdline /proc/cmdline)"
 KSCFG="$(kickseed_file "$KS")"
 
 case $KSCFG in
-	''|/cdrom/*|/floppy/*|$SPOOL/fetch/http/*)
+	/cdrom/*)
+		if [ -x /var/lib/dpkg/info/cdrom-detect.postinst ]; then
+			/lib/kickseed/kickseed-udpkg cdrom-detect || true
+		else
+			logger -t kickseed "cdrom-detect not installed; cannot read $KSCFG"
+			exit 1
+		fi
+		;;
+	/floppy/*)
+		mountfloppy || true
+		trap 'umount /floppy || true' EXIT HUP INT QUIT TERM
+		;;
+esac
+
+case $KSCFG in
+	''|$SPOOL/fetch/http/*)
 		# not handled in initrd (yet?)
 		: ;;
 	*)
