[project @ Arch-1:colin.watson@canonical.com--2005%kickseed--mainline--0--patch-101] merge network-kickseed into initrd-kickseed Merge network-kickseed into initrd-kickseed. If reading a Kickstart file from the network, install ethdetect and netcfg using anna (if necessary, and detecting the CD-ROM first if installing from CD-ROM) and configure them using udpkg to arrange for the network to be accessible.
Original author: Colin Watson <colin.watson@canonical.com>
Date: 2005-02-25 20:07:10+00:00

git-svn-id: svn://svn.debian.org/svn/d-i/trunk@47393 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/kickseed/initrd-kickseed b/packages/kickseed/initrd-kickseed
--- a/packages/kickseed/initrd-kickseed
+++ b/packages/kickseed/initrd-kickseed
@@ -36,8 +36,33 @@ preseed_relative () {
 	fi
 }
 
+fetch_url () {
+	local url="$1"
+	local file="$2"
+	iters=0
+	while [ $iters -lt 3 ]; do
+		# TODO proxy support? Would it be useful?
+		# TODO add progress bar
+		if wget -q "$url" -O "$file" 2>&1 | logger -t kickseed; then
+			return 0
+		fi
+		iters=$(($iters + 1))
+	done
+	return 1
+}
+
 KS="$(kickseed_cmdline /proc/cmdline)"
 KSCFG="$(kickseed_file "$KS")"
+
+case $KS in
+	http://*/*)
+		logger -t kickseed "Downloading kickstart file from $KS"
+		if ! fetch_url "$KS" "$KSCFG"; then
+			logger -t kickseed "... failed"
+			exit 1
+		fi
+		;;
+esac
 
 case $KSCFG in
 	/floppy/*)
@@ -47,7 +72,7 @@ case $KSCFG in
 esac
 
 case $KSCFG in
-	''|$SPOOL/fetch/http/*)
+	'')
 		# not handled in initrd (yet?)
 		: ;;
 	*)
