Use chroot-setup.sh to mount /proc and /sys in the target when running apt-cdrom (closes: #595903).  This would normally need di-utils 1.80; but to avoid breaking d-i squeeze alpha 1 (and possibly beta 1) initrds, I've temporarily copied a chunk of code from chroot-setup.sh into two apt-setup generator scripts.  This should be cleaned up once compatibility with older initrds is no longer necessary.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@64811 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/apt-setup/generators/41cdset b/packages/apt-setup/generators/41cdset
--- a/packages/apt-setup/generators/41cdset
+++ b/packages/apt-setup/generators/41cdset
@@ -2,6 +2,34 @@
 set -e
 
 . /usr/share/debconf/confmodule
+. /lib/chroot-setup.sh
+
+# This code is copied from chroot-setup.sh, and is needed until after a d-i
+# release whose initrds contain a sufficiently new version of di-utils.
+if ! type chroot_cleanup_localmounts >/dev/null 2>&1; then
+	# Variant of chroot_cleanup that only cleans up chroot_setup's mounts.
+	chroot_cleanup_localmounts () {
+		rm -f /target/usr/sbin/policy-rc.d
+		mv /target/sbin/start-stop-daemon.REAL /target/sbin/start-stop-daemon
+		if [ -x /target/sbin/initctl.REAL ]; then
+			mv /target/sbin/initctl.REAL /target/sbin/initctl
+		fi
+
+		# Undo the mounts done by the packages during installation.
+		# Reverse sorting to umount the deepest mount points first.
+		# Items with count of 1 are new.
+		for dir in $( (cat /tmp/mount.pre /tmp/mount.pre /tmp/mount.post ) | \
+			     sort -r | uniq -c | grep "^[[:space:]]*1[[:space:]]" | \
+			     sed "s/^[[:space:]]*[0-9][[:space:]]//"); do
+			if ! umount $dir; then
+				logger -t $0 "warning: Unable to umount '$dir'"
+			fi
+		done
+		rm -f /tmp/mount.pre /tmp/mount.post
+
+		rm -f /var/run/chroot-setup.lock
+	}
+fi
 
 file="$1"
 
@@ -32,6 +60,11 @@ if [ "$ROOT" ]; then
 
 	# We can only change CDs if current CD is unmounted
 	$logoutput umount /cdrom || true
+
+	chroot_setup
+	# Needed until after a d-i release with new enough di-utils.
+	mountpoints > /tmp/mount.post
+	trap chroot_cleanup_localmounts EXIT HUP INT QUIT TERM
 fi
 
 tmp=$($chroot $ROOT tempfile)
