Stop abusing $RET in generators/50mirror for things other than debconf.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@60920 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/apt-setup/generators/50mirror b/packages/apt-setup/generators/50mirror
--- a/packages/apt-setup/generators/50mirror
+++ b/packages/apt-setup/generators/50mirror
@@ -112,11 +112,11 @@ if [ -e /cdrom/.disk/base_installable ]; then
 	fi
 
 	while true; do
-		RET=0
-		choose-mirror -n || RET=$?	# no progress bar
-		if [ $RET -eq 0 ]; then
+		CODE=0
+		choose-mirror -n || CODE=$?	# no progress bar
+		if [ $CODE -eq 0 ]; then
 			break
-		elif [ $RET -eq 10 ]; then
+		elif [ $CODE -eq 10 ]; then
 			# User backed out of choose-mirror
 			db_input critical apt-setup/no_mirror
 			db_go || exit 10
@@ -126,8 +126,8 @@ if [ -e /cdrom/.disk/base_installable ]; then
 				exit 1
 			fi
 		else
-			logger -t apt-setup "choose-mirror failed with error code $RET"
-			exit $RET
+			logger -t apt-setup "choose-mirror failed with error code $CODE"
+			exit $CODE
 		fi
 	done
 fi
