Only ask to continue without mirror if user backed out of choose-mirror, not for other error conditions
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@49477 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/apt-setup/generators/50mirror b/packages/apt-setup/generators/50mirror
--- a/packages/apt-setup/generators/50mirror
+++ b/packages/apt-setup/generators/50mirror
@@ -83,7 +83,8 @@ if [ -e /cdrom/.disk/base_installable ]; then
 		choose-mirror -n || RET=$?	# no progress bar
 		if [ $RET -eq 0 ]; then
 			break
-		else
+		elif [ $RET -eq 10 ]; then
+			# User backed out of choose-mirror
 			db_input critical apt-setup/no_mirror
 			db_go || exit 10
 
@@ -91,6 +92,9 @@ if [ -e /cdrom/.disk/base_installable ]; then
 			if [ "$RET" = true ]; then
 				exit 1
 			fi
+		else
+			logger -t apt-setup "choose-mirror failed with error code $RET"
+			exit $RET
 		fi
 	done
 fi
