- Build English first and fail on errors; this avoids exporting errors to PO files - Support retrying a build after fixing the cause for a build failure - Make it possible to specify extra languages to build on the command line - Check against running more than one build at the same time - General review and coding style improvements - Hope nothing broke...
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@44858 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/manual-daily/build-manual b/scripts/manual-daily/build-manual
--- a/scripts/manual-daily/build-manual
+++ b/scripts/manual-daily/build-manual
@@ -3,48 +3,80 @@
 [ -f ~/.di-manual-daily ] || exit 1
 . ~/.di-manual-daily
 
-EXTRA_LANGS=""
-
 mainlog=$logdir/main.log
 
+usage() {
+    if [ "$@" ]; then
+        echo "Error: $@"
+        echo
+    fi
+    echo "Usage: $(basename $0) [-r|--retry|--restart] [language ...]"
+    echo "If any languages are specified, they will also be built if not updated."
+    exit 1
+}
+
 ## Function to check result of executed programs and exit on error
-checkfatal () {
+checkfatal() {
     if [ ! "$1" = "0" ]; then
         echo "Unexpected error $1 while $2" >>$mainlog
         touch $ROOT/do_not_build
         echo "!!!! Autobuilding has been disabled !!!!" >>$mainlog
+        rm -f $ROOT/lockfile
         exit 999
     fi
 }
 
-do_extra () {
-    for EL in $EXTRA_LANGS; do
-        [ "$EL" = "$1" ] && return 0
+uses_po() {
+    local lang=$1
+
+    if [ -d "../po/$lang" ] && [ ! -d "../$lang/.svn" ]; then
+        return 0
+    fi
+    return 1
+}
+
+is_updated() {
+    local lang=$1
+
+    if uses_po "$lang"; then
+        grepexp="^[UA].[[:space:]]*po/${lang}/.*\.po$"
+    else
+        grepexp="^[UA].[[:space:]]*${lang}/"
+    fi
+
+    if egrep -q $grepexp $logdir/svn_up.log; then
+        return 0
+    fi
+    return 1
+}
+
+do_extra() {
+    local lang
+    for lang in $EXTRA_LANGS; do
+        [ "$lang" = "$1" ] && return 0
     done
     return 1
 }
 
-update_templates () {
+update_templates() {
     echo "Generating integrated XML files and POT files..."
     ./scripts/merge_xml en
-    RET=$?; [ $RET -ne 0 ] && return 1
+    [ $? -ne 0 ] && return 1
     ./scripts/update_pot
-    RET=$?; [ $RET -ne 0 ] && return 1
+    [ $? -ne 0 ] && return 1
     return 0
 }
 
-update_po () {
+update_po() {
     ./scripts/update_po $1
-    RET=$?; [ $RET -ne 0 ] && return $RET
-    return 0
+    return $?
 }
-generate_xml () {
+generate_xml() {
     ./scripts/create_xml $1
-    RET=$?; [ $RET -ne 0 ] && return $RET
-    return 0
+    return $?
 }
 
-get_formats () {
+get_formats() {
     formats=""
     for format in html pdf ps txt; do
         case $format in
@@ -53,47 +85,47 @@ get_formats () {
             ps)    GETCOL=5;;
             txt)   GETCOL=6;;
         esac
-        if [ "$(egrep "^$1[[:space:]]" $ROOT/bin/langlist | cut -f $GETCOL)" = "Y" ] ; then
+        if [ "$(egrep "^$1[[:space:]]" $ROOT/bin/langlist | cut -f $GETCOL)" = "Y" ]; then
             formats="$formats $format"
         fi
     done
     echo "$(echo "$formats" | sed "s:^ ::")"
 }
 
-update_from_svn () {
-    echo "" >>$mainlog
+update_from_svn() {
+    echo >>$mainlog
     echo "Performing SVN update..." >>$mainlog
-    svn up &>$logdir/svn_up.log
+    svn up >>$logdir/svn_up.log 2>&1
     RESULT=$?
-    if [ ! "$RESULT" = "0" ] ; then
+    if [ ! $RESULT = 0 ]; then
         echo "SVN update failed with code $RESULT" >>$mainlog
-        echo "" >>$mainlog
+        echo >>$mainlog
         cat $logdir/svn_up.log >>$mainlog
+        rm -f $ROOT/lockfile
         exit 1
     fi
-    if svn st 2>/dev/null | grep -q "^C" ; then
+    if svn st 2>/dev/null | grep -q "^C"; then
         checkfatal "C" "checking for conflicts after 'svn up'"
     fi
 }
 
-commit_to_svn () {
+commit_to_svn() {
     echo "Committing changes in manual/po to SVN..." >>$mainlog
-    : >$logdir/svn_ci.log
     SVN_NEW_LIST=$(svn st po/pot/ 2>/dev/null | grep "^\?[[:space:]].*\.pot" | sed "s/^\?[[:space:]]*//")
-    if [ "$SVN_NEW_LIST" ] ; then
+    if [ "$SVN_NEW_LIST" ]; then
         echo "Adding new POT files:" >>$logdir/svn_ci.log
         for SVN_NEW in $SVN_NEW_LIST; do
             svn add $SVN_NEW >>$logdir/svn_ci.log 2>&1
             checkfatal "$?" "running 'svn add' on $SVN_NEW"
         done
     fi
-    if svn st po/ 2>/dev/null | grep -q "^[AM]" ; then
+    if svn st po/ 2>/dev/null | grep -q "^[AM]"; then
 #       echo "Actual commit disabled, showing svn st:" >>$logdir/svn_ci.log
 #       svn st po/ 2>/dev/null >>$logdir/svn_ci.log 2>&1
         echo "Committing changed files:" >>$logdir/svn_ci.log
         svn ci po/ -m "[SILENT_COMMIT] Update of POT and PO files for the manual" >>$logdir/svn_ci.log 2>&1
         checkfatal "$?" "committing POT/PO files to SVN"
-        if svn st po/ 2>/dev/null | grep -q "^C" ; then
+        if svn st po/ 2>/dev/null | grep -q "^C"; then
             checkfatal "C" "checking for conflicts in manual/po after 'svn ci'"
         fi
     else
@@ -101,128 +133,24 @@ commit_to_svn () {
     fi
 }
 
-# We want the manual files group writable
-umask 0002
+build_lang() {
+    local lang=$1
 
-[ -f "$ROOT/do_not_build" ] && exit 1
-
-[ -e "$source" ] && cd $source || exit 1
-
-[ -f "$ROOT/bin/langlist" ] || exit 1
-[ -f "$ROOT/bin/archlist" ] || exit 1
-
-# Order of languages is order in list.
-languages=`egrep -v "^[[:space:]]*(|#.*)$" $ROOT/bin/langlist | cut -f 1`
-
-# Order of architectures is order in list.
-architectures=`egrep -v "^[[:space:]]*(|#.*)$" $ROOT/bin/archlist | cut -f 1`
-
-## Create directories
-[ -e "$destination" ] || mkdir -p "$destination"
-[ -e "$logdir" ] || mkdir -p "$logdir"
-
-## Clean old files
-rm -R $destination/* &>/dev/null
-
-export manual_release="etch"
-export manual_target="for_alioth"
-
-echo "Starting D-I Manual build -- `date -u`" >$mainlog
-
-update_from_svn
-
-echo "" >>$mainlog
-# Prepare for the build: generate XML for translations using PO files
-# Note: English should always be processed first
-EN_UPDATED=""
-echo "Updating POT and PO files..." >>$mainlog
-for lang in $languages; do
-    langlog=$logdir/$lang.log
-    : >$langlog
-
-    # Check whether language uses PO files for translation
-    USES_PO=""
-    grepexp="^[UA].[[:space:]]*${lang}/"
-    if [ -d "./po/$lang" ] && [ ! -d "./$lang/.svn" ] ; then
-        USES_PO="1"
-        grepexp="^[UA].[[:space:]]*po/${lang}/.*\.po$"
-    fi
-
-    LANG_UPDATED=""
-    if egrep -q $grepexp $logdir/svn_up.log || do_extra "$lang"; then
-        LANG_UPDATED="1"
-    fi
-
-    if [ "$lang" = "en" ] ; then
-        # For English (if updated), we need to merge the XML and update the POT files
-        if [ -n "$LANG_UPDATED" ] || [ ! -d "$source/integrated/en" ] ; then
-            EN_UPDATED="1"
-            update_templates >>$mainlog 2>&1
-            checkfatal "$?" "updating templates"
-            echo "" >>$mainlog
-        fi
-    else
-        # For other languages, we may need to update PO and generate XML files
-        # PO files are updated for all languages if there was an update for English
-        [ -n "$LANG_UPDATED" ] && \
-            echo "Preparing build for language $lang - `date -u`" >>$langlog
-
-        if [ -d "./po/$lang" ] ; then
-            if [ -n "$LANG_UPDATED" ] || [ -n "$EN_UPDATED" ] ; then
-                echo "Info: updating PO files for $lang" >>$mainlog
-                update_po $lang >>$langlog 2>&1
-                checkfatal "$?" "updating po for $lang"
-            fi
-        fi
-
-        if [ -n "$LANG_UPDATED" ] ; then
-            if [ -z "$USES_PO" ] ; then
-                echo "Info: building manual from XML files" >>$langlog
-            else
-                echo "Info: building manual from PO files" >>$langlog
-                generate_xml $lang >>$langlog 2>&1
-                checkfatal "$?" "generating xml for $lang"
-                echo "Info: generation of XML files complete" >>$langlog
-            fi
-            echo "" >>$langlog
-        fi
-    fi
-done
-
-echo "" >>$mainlog
-# Commit updates to POT and PO files to SVN
-commit_to_svn
-
-cd ./build
-NR_BUILD=0
-
-echo "" >>$mainlog
-# Note: English should always be processed first
-for lang in $languages; do
-    # Check whether language uses PO files for translation
-    USES_PO=""
-    grepexp="^[UA].[[:space:]]*${lang}/"
-    if [ -d "../po/$lang" ] && [ ! -d "../$lang/.svn" ] ; then
-        USES_PO="1"
-        grepexp="^[UA].[[:space:]]*po/${lang}/.*\.po$"
-    fi
-
-    # Test if language was updated
-    if egrep -q $grepexp $logdir/svn_up.log || do_extra "$lang"; then
-        BUILDRESULT=0
-        BUILDIND=`egrep "^$lang[[:space:]]" $ROOT/bin/langlist | cut -f 2`
-        case "$BUILDIND" in
-            "Y")
+    BUILDRESULT=0
+    cd $source/build
+    if is_updated "$lang" || do_extra "$lang"; then
+        case "$(egrep "^$lang[[:space:]]" $ROOT/bin/langlist | cut -f 2)" in
+            Y)
                 formats=$(get_formats $lang)
                 echo "Language $lang - full build: $formats" >>$mainlog
                 buildarchs=$architectures
                 ;;
-            "S")
+            S)
                 formats=$(get_formats $lang)
                 echo "Language $lang - partial build: $formats" >>$mainlog
                 buildarchs="i386"
                 ;;
-            "N")
+            N)
                 echo "Language $lang - updated; not building" >>$mainlog
                 continue
                 ;;
@@ -235,18 +163,18 @@ for lang in $languages; do
             echo "NOTE: extra build!" >>$mainlog
         fi
 
-        if [ -z "$formats" ] ; then
+        if [ -z "$formats" ]; then
             echo "No output formats specified for $lang" >>$mainlog
             continue
         fi
 
         langlog=$logdir/$lang.log
-        echo "Starting build for language $lang - `date -u`" >>$langlog
-        echo "" >>$langlog
+        echo "Starting build for language $lang - $(date -u)" >>$langlog
+        echo >>$langlog
 
         for arch in $buildarchs; do
             destsuffix="${lang}.${arch}"
-            if [ "$BUILDRESULT" = "0" ] ; then
+            if [ $BUILDRESULT = 0 ]; then
                 echo "Building manual for $arch" >>$langlog
                 echo -n "  $arch" >>$mainlog
 
@@ -254,13 +182,13 @@ for lang in $languages; do
                 RESULT=$?
 
                 cat $langlog.arch >>$langlog
-                echo "" >>$langlog
-                case "$RESULT" in
+                echo >>$langlog
+                case $RESULT in
                     0|2)
-                        if [ "$RESULT" = "2" ] ; then
+                        if [ $RESULT = 2 ]; then
                             # Check if at least html was built correctly; if not, we won't upload
                             # As index.html is the last file created, we check that
-                            if [ -s build.out/html/index.html ] ; then
+                            if [ -s build.out/html/index.html ]; then
                                 echo "Error: error building some output format(s) for '$arch'" >>$langlog
                                 echo "  Error: error building some output format(s) for '$lang.$arch'" >>$mainlog
                             else
@@ -275,7 +203,7 @@ for lang in $languages; do
                         echo "Errors while building manual for $arch" >>$langlog
                         ;;
                 esac
-                if [ "$BUILDRESULT" = "0" ] ; then
+                if [ $BUILDRESULT = 0 ]; then
                     mkdir "$destination/$destsuffix"
                     # First copy placeholder docs for pdf and txt
                     echo $formats | grep -q "pdf" && \
@@ -287,8 +215,8 @@ for lang in $languages; do
                     mv ./build.out/install.$lang.* "$destination/$destsuffix"
                 else
                     echo "Note: remaining architectures will not be built" >>$langlog
-                    echo "" >>$langlog
-                    echo "" >>$mainlog
+                    echo >>$langlog
+                    echo >>$mainlog
                     echo "  Error: fatal error building manual for $lang.$arch" >>$mainlog
                 fi
                 ./clear.sh
@@ -301,20 +229,19 @@ for lang in $languages; do
         done
 
         rm $langlog.arch
-        [ "$BUILDRESULT" = "0" ] && echo "" >>$mainlog
+        [ $BUILDRESULT = 0 ] && echo >>$mainlog
 
         # Upload logfile to people.debian.org
         scp $logdir/$lang.log people.debian.org:public_html/d-i_manual/log/
-        if [ $? = 0 ] ; then
+        if [ $? = 0 ]; then
             echo "  Upload of $lang.log success" >>$mainlog
         else
             echo "  Upload of $lang.log failed" >>$mainlog
         fi
 
         # Check if any architectures have actually been built
-        grepexp="${lang}\."
-        if ls $destination | grep -q "$grepexp" ; then
-            NR_BUILD=$(($NR_BUILD + 1))
+        if ls $destination | grep -q "$lang\."; then
+            NR_BUILDS=$(($NR_BUILDS + 1))
         fi
 
         # Sleep a bit to allow the system to cool down...
@@ -322,33 +249,168 @@ for lang in $languages; do
     else
         echo "No updates for $lang" >>$mainlog
     fi
+    return $BUILDRESULT
+}
+
+# We want the manual files group writable
+umask 0002
+
+RETRY=""
+EXTRA_LANGS=""
+while true; do
+    case $1 in
+        "")
+            break ;;
+        -r|--retry|--restart)
+            RETRY=1 ;;
+        -*)
+            usage "unrecognized option '$1'" ;;
+        *)
+            EXTRA_LANGS="$EXTRA_LANGS $1" ;;
+    esac
+    shift
 done
 
-## Extract preseeding example from the manual
+for lang in $EXTRA_LANGS; do
+    if ! grep -q "^${lang}[[:space:]]" $ROOT/bin/langlist; then
+        usage "unknown language '$lang'"
+    fi
+done
+
+if [ "$RETRY" ]; then
+    rm -f $ROOT/do_not_build
+fi
+
+[ -f $ROOT/do_not_build ] && exit 1
+[ -f $ROOT/lockfile ] && exit 1 || touch $ROOT/lockfile
+
+[ -e "$source" ] && cd $source || exit 1
+
+[ -f $ROOT/bin/langlist ] || exit 1
+[ -f $ROOT/bin/archlist ] || exit 1
+
+# Order of translations is order in list
+translations=$(egrep -v "^[[:space:]]*(|#.*)$" $ROOT/bin/langlist | cut -f 1 | \
+	grep -v "^en$")
+
+# Order of architectures is order in list
+architectures=$(egrep -v "^[[:space:]]*(|#.*)$" $ROOT/bin/archlist | cut -f 1)
+
+## Create directories
+[ -e "$destination" ] || mkdir -p "$destination"
+[ -e "$logdir" ] || mkdir -p "$logdir"
+
+## Clean old files
+rm -R $destination/* &>/dev/null
+
+export manual_release="etch"
+export manual_target="for_alioth"
+
+if [ -z "$RETRY" ]; then
+    : >$logdir/svn_up.log
+    : >$logdir/svn_ci.log
+    echo "Starting D-I Manual build -- $(date -u)" >$mainlog
+else
+    echo >>$mainlog
+    echo >>$mainlog
+    echo "Starting D-I Manual build (RETRY) -- $(date -u)" >>$mainlog
+fi
+
+update_from_svn
+echo >>$mainlog
+
+NR_BUILDS=0
+
+# Build the manual for English
+EN_UPDATED=""
+if lang_updated en; then
+    EN_UPDATED=1
+    langlog=$logdir/en.log
+    : >$langlog
+    echo "Preparing build for language $lang - $(date -u)" >>$langlog
+    echo "Info: building manual from XML files" >>$langlog
+
+    build_lang en
+    checkfatal "$?" "build for English"
+    echo >>$mainlog
+fi
+
+# Do we need to merge the XML and update the POT files?
+cd $source
+if lang_updated en || [ ! -d "$source/integrated/en" ]; then
+    update_templates >>$mainlog 2>&1
+    checkfatal "$?" "updating templates"
+    echo >>$mainlog
+fi
+
+# Prepare for the build of translations
+echo "Updating POT and PO files..." >>$mainlog
+for lang in $translations; do
+    langlog=$logdir/$lang.log
+    : >$langlog
+
+    if is_updated "$lang" || do_extra "$lang"; then
+        echo "Preparing build for language $lang - $(date -u)" >>$langlog
+    fi
+
+    # For translations, we may need to update PO and generate XML files
+    # PO files are updated for all translations if there was an update for English
+    if [ -d "./po/$lang" ]; then
+        if lang_updated "$lang" || [ "$EN_UPDATED" ]; then
+            echo "Info: updating PO files for $lang" >>$mainlog
+            update_po $lang >>$langlog 2>&1
+            checkfatal "$?" "updating po for $lang"
+        fi
+    fi
+
+    if is_updated "$lang" || do_extra "$lang"; then
+        if uses_po "$lang"; then
+            echo "Info: building manual from PO files" >>$langlog
+            generate_xml $lang >>$langlog 2>&1
+            checkfatal "$?" "generating xml for $lang"
+            echo "Info: generation of XML files complete" >>$langlog
+        else
+            echo "Info: building manual from XML files" >>$langlog
+        fi
+        echo >>$langlog
+    fi
+done
+
+echo >>$mainlog
+# Commit updates to POT and PO files to SVN
+commit_to_svn
+
+echo >>$mainlog
+# Build translations
+for lang in $translations; do
+    build_lang $lang
+done
+
+## Extract preconfiguration example from the manual
 PRESEED="../en/appendix/preseed.xml"
-if [ -f $PRESEED ] && [ -x preseed.pl ] ; then
+if [ -f $PRESEED ] && [ -x preseed.pl ]; then
     ./preseed.pl -r $manual_release $PRESEED >$destination/example-preseed.txt
 fi
 
 
-echo "" >>$mainlog
+echo >>$mainlog
 ## Copy the created files to alioth.debian.org
-if [ $NR_BUILD -gt 0 ] ; then
-    echo "$NR_BUILD languages have been (partially) built." >>$mainlog
+if [ $NR_BUILDS -gt 0 ]; then
+    echo "$NR_BUILDS languages have been (partially) built." >>$mainlog
 
-    echo "" >>$mainlog
+    echo >>$mainlog
     echo "Create index page:" >>$mainlog
     $ROOT/bin/create-index
 
-    echo "" >>$mainlog
+    echo >>$mainlog
     cd $destination
 
     echo "rsyncing files to alioth..." >>$mainlog
     rsync -qz --perms * alioth\:d-i_web/manual/ >>$mainlog 2>&1
     # rsync subdirectories individually so we can also delete obsolete files
     for i in $(find . -type d | grep -v "^\.$"); do
-    	rsync -qzr --perms --delete "$i" alioth\:d-i_web/manual/ >>$mainlog 2>&1
-	checkfatal "$?" "rsync of '$i'"
+        rsync -qzr --perms --delete "$i" alioth\:d-i_web/manual/ >>$mainlog 2>&1
+        checkfatal "$?" "rsync of '$i'"
     done
 else
     echo "No languages built." >>$mainlog
@@ -357,7 +419,8 @@ fi
 # Clean up some
 find $source/po -name "*.po~" -exec rm {} +
 
-echo "" >>$mainlog
-echo "Done -- `date -u`" >>$mainlog
+echo >>$mainlog
+echo "Done -- $(date -u)" >>$mainlog
+rm -r $ROOT/lockfile
 
 exit 0
