Better error hanling between scripts
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@39275 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/manual-daily/build-main b/scripts/manual-daily/build-main
--- a/scripts/manual-daily/build-main
+++ b/scripts/manual-daily/build-main
@@ -1,8 +1,13 @@
 #!/bin/bash
 ROOT=/home/rfjp/d-i
 
-$ROOT/bin/build-manual
-$ROOT/bin/mail-logs
+RET=0
+$ROOT/bin/build-manual || RET=$?
+
+if [ $RET = 0 ] || [ $RET = 999 ]; then
+	$ROOT/bin/mail-logs
+else
+	echo "Build failed, not sending logs"
+fi
 
 exit 0
-
