- CC the main log to myself for release coordination - Use a temporary directory instead of temporary files - Some coding cleanup Untested, so hope I did not break anything
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@51034 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/manual-daily/mail-logs b/scripts/manual-daily/mail-logs
--- a/scripts/manual-daily/mail-logs
+++ b/scripts/manual-daily/mail-logs
@@ -11,6 +11,10 @@ logpage="http://d-i.alioth.debian.org/manual/logs"
 
 [ -e "$logdir" ] && cd $logdir || exit 1
 
+if ! tmpdir=$(mktemp -td mail-logs.XXXXXX); then
+	exit 1
+fi
+
 add-svnlog () {
     echo "" >>$mainlog
     echo "" >>$mainlog
@@ -31,56 +35,53 @@ if [ -f $ROOT/do_not_build ] ; then
 fi
 
 # Only create mails for languages that were built
-for lang in $(egrep "Language .* - (full|partial) build:" $mainlog | \
-	      cut -d " " -f 2 | sort -u); do
-    grepexp="^$lang[[:space:]]"
-    mailaddress=$(egrep "$grepexp" $ROOT/bin/langlist | cut -f 8)
+for lang in $(grep -E "Language .* - (full|partial) build:" $mainlog | \
+        cut -d " " -f 2 | sort -u); do
+    mailaddress=$(grep -E "^$lang[[:space:]]" $ROOT/bin/langlist | cut -f 8)
 
     # Check for errors during build
     BUILD_ERRORS=0
-    egrep -v "^(Writing|Info:|Warning:|dvips:|- (upd|cre)ating|found empty tag para)" \
-             $logdir/$lang.log >/tmp/build_log.$$
-    if egrep -v -q "^(|Error: no ID for constraint linkend:.*|(Preparing|Starting) build.*|Building manual.*|(Updating PO|Creating XML) files for language.*)$" \
-                /tmp/build_log.$$ ; then
+    grepexp="^((Preparing|Starting) build|Building manual|(Updating PO|Creating XML) files for language|- (upd|cre)ating|Writing|Info:|Warning:|dvips:|found empty tag para|Error: no ID for constraint linkend:|$)"
+    if grep -Eqv "$grepexp" $logdir/$lang.log; then
         BUILD_ERRORS=1
     fi
 
     # Create header file
-    echo "From: $NAME_FROM <$MAIL_FROM>" >/tmp/header.$$
-    echo "To: $mailaddress" >>/tmp/header.$$
-#   echo "BCC: fjp@fjphome.nl" >>/tmp/header.$$
-    echo "Reply-To: $NAME_FROM <$MAIL_FROM>" >>/tmp/header.$$
-    if [ "$BUILD_ERRORS" = "0" ] ; then
-        echo "Subject: [D-I Manual] Build log for $lang ($builddate)" >>/tmp/header.$$
+    echo "From: $NAME_FROM <$MAIL_FROM>" >$tmpdir/header
+    echo "To: $mailaddress" >>$tmpdir/header
+#   echo "CC: elendil@planet.nl" >>$tmpdir/header
+    echo "Reply-To: $NAME_FROM <$MAIL_FROM>" >>$tmpdir/header
+    if [ "$BUILD_ERRORS" = "0" ]; then
+        echo "Subject: [D-I Manual] Build log for $lang ($builddate)" >>$tmpdir/header
     else
-        echo "Subject: [D-I Manual] Build log for $lang ($builddate) - ERRORS DURING BUILD" >>/tmp/header.$$
+        echo "Subject: [D-I Manual] Build log for $lang ($builddate) - ERRORS DURING BUILD" >>$tmpdir/header
     fi
 
     # Create message file
-    if [ "$BUILD_ERRORS" = "0" ] ; then
-        cat $ROOT/bin/msgtxt.ok >/tmp/message.$$
+    if [ "$BUILD_ERRORS" = "0" ]; then
+        cat $ROOT/bin/msgtxt.ok >$tmpdir/message
     else
-        cat $ROOT/bin/msgtxt.fail >/tmp/message.$$
+        cat $ROOT/bin/msgtxt.fail >$tmpdir/message
     fi
 
     ATTACHMENT=""
-    # Check whether upload of logfile to home.tiscali.nl was successful
-    if egrep -q "Upload of $lang.log success" $mainlog ; then
-        echo "A log of the build is available at:" >>/tmp/message.$$
-        echo "- $logpage/$lang.log" >>/tmp/message.$$
+    # Check whether upload of logfile was successful
+    if grep -Eq "Upload of $lang.log success" $mainlog ; then
+        echo "A log of the build is available at:" >>$tmpdir/message
+        echo "- $logpage/$lang.log" >>$tmpdir/message
     else
-        echo "A log of the build has been attached." >>/tmp/message.$$
+        echo "A log of the build has been attached." >>$tmpdir/message
         # Create attachment
         gzip -c $logdir/$lang.log >$logdir/$lang.log.gz
         ATTACHMENT="-a $logdir/$lang.log.gz"
     fi
 
-    cat $ROOT/bin/msgtxt.common >>/tmp/message.$$
-    grepexp="^([UAD].[[:space:]]*(po/|)${lang}/|Updated to revision)"
-    egrep "$grepexp" $logdir/svn_up.log >>/tmp/message.$$
+    cat $ROOT/bin/msgtxt.common >>$tmpdir/message
+    grep -E "^([UAD].[[:space:]]*(po/|)$lang/|Updated to revision)" \
+            $logdir/svn_up.log >>$tmpdir/message
 
     # Mail message
-    mutt -H /tmp/header.$$ $ATTACHMENT </tmp/message.$$
+    mutt -H $tmpdir/header $ATTACHMENT <$tmpdir/message
 
     [ -f $logdir/$lang.log.gz ] && rm $logdir/$lang.log.gz
 done
@@ -89,7 +90,7 @@ echo "" >>$mainlog
 echo "Build successfull; logmails have been sent!" >>$mainlog
 add-svnlog
 
-mutt -s "D-I Manual build success ($builddate)" $MAIL_FROM <$mainlog
+mutt -s "D-I Manual build success ($builddate)" -c elendil@planet.nl $MAIL_FROM <$mainlog
 
-rm /tmp/*.$$ &>/dev/null
+rm -rf $tmpdir
 exit 0
