Bail-out much earlier if a filesystem image cannot be found
If there was an error locating a live image, live-installer continues and
eventually fails somewhere inside the live-installer post-installation
hooks with no sensible error message.

Although this patch does not display a debconf warning, it at least halts
the installation and emits something to syslog.

Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>


git-svn-id: svn://svn.debian.org/svn/d-i/trunk@53748 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/live-installer/debian/postinst b/packages/live-installer/debian/postinst
--- a/packages/live-installer/debian/postinst
+++ b/packages/live-installer/debian/postinst
@@ -17,6 +17,7 @@ mode="$RET"
 install_live_system () {
 	# Look at
 	PLACES=""
+	PLACE_FOUND=0
 
 	# Load filesystem support
 	for script in $(ls /lib/live-installer/*); do
@@ -28,6 +29,8 @@ install_live_system () {
 
 		SUPPORT=$(echo $place | sed 's,.*\.\(.*\)$,\1,g')
 		info "Using $SUPPORT support for $place"
+
+		PLACE_FOUND=1
 
 		eval ${SUPPORT}_prepare
 		STEPS=$(eval ${SUPPORT}_count)
@@ -58,6 +61,11 @@ install_live_system () {
 		done
 		IFS=$OLD_IFS
 	done
+
+	if [ ${PLACE_FOUND} -eq 0 ]; then
+		error "Could not find any live images"
+		exit 1
+	fi
 
 	# if we're dumping it, we need to set boot=live
 	if [ "$mode" = live ]; then
