Identify languages by language code instead of language name
- The language code moves to the first field of the languagelist and
  is now the full language code (including country specifier for
  languages that need it).
- Templates gain the Choices-C field containing country codes and are
  renamed to reflect the fact that they use codes instead of names.
- Set the languagelist to 'en' for the C locale to replace the special
  case the old langcode field had for C.
- Clean up mktemplates.language (remove unused code).


git-svn-id: svn://svn.debian.org/svn/d-i/trunk@51845 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/localechooser/languagemap b/packages/localechooser/languagemap
--- a/packages/localechooser/languagemap
+++ b/packages/localechooser/languagemap
@@ -13,12 +13,11 @@ for list in /etc/languagelist /usr/share/localechooser/languagelist ./languageli
 	fi
 done
 
-log "Language = '$LANGNAME'"
+log "Language = '$LANGUAGE'"
 
-line=$(grep "^$LANGNAME;" $languages || true)
+line=$(grep "^$LANGUAGE;" $languages || true)
 log "line=$line"
 
-LANGUAGE=""
 COUNTRY=""
 FALLBACKLOCALE=""
 LOCALE=""
@@ -31,17 +30,18 @@ if [ "$line" ] ; then
 	set $line
 	IFS="$OLD_IFS"
 
-	if [ "$3" ]; then LANGUAGE="$3" ; fi
-	if [ "$4" ]; then COUNTRY="$4" ; fi
-	if [ "$5" ]; then FALLBACKLOCALE="$5" ; LOCALE="$5" ; fi
-	if [ "$6" ]; then LANGUAGELIST="$6"; fi
-	if [ "$7" ]; then CONSOLE="$7"; fi
+	if [ "$3" ]; then COUNTRY="$3" ; fi
+	if [ "$4" ]; then FALLBACKLOCALE="$4" ; LOCALE="$4" ; fi
+	if [ "$5" ]; then LANGUAGELIST="$5"; fi
+	if [ "$6" ]; then CONSOLE="$6"; fi
 
 	if [ -z "$LANGUAGELIST" ] ; then
 		LANGUAGELIST="$LANGUAGE"
 	fi
 else
-	log "error: Unable to locate info for language '$LANGNAME'"
-	LOCALE=C
+	log "error: Unable to locate info for language '$LANGUAGE'"
+	LANGUAGE=C
 	COUNTRY=US
+	LOCALE=C
+	LANGUAGELIST=en
 fi
