Don't re-download files if checksum match.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@61100 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/netboot-assistant/di-netboot-assistant b/netboot-assistant/di-netboot-assistant
--- a/netboot-assistant/di-netboot-assistant
+++ b/netboot-assistant/di-netboot-assistant
@@ -379,6 +379,19 @@ remove_repocaches() {
 	[ "$DEBUG" ] && set +x
 }
 
+check_sum() {
+	fname=$1
+	actual_file=$2
+
+	if [ ! -f "$actual_file" -o ! -f "$CSUM_FILE" ]; then
+		return 1
+	fi
+	sum=$($CSUM $actual_file | cut -d " " -f 1)
+	if ! grep -qiE "^$sum[[:blank:]]+(\./|)$fname[[:blank:]]*$" $CSUM_FILE ; then
+		return 1
+	fi
+	return 0
+}
 
 fetch_files() {
 	local release="$1"
@@ -407,6 +420,8 @@ fetch_files() {
 	metadatafile="${DL_CACHE}/$(echo ${repo_loc}~~${release}--${arch}.meta | url2filename)"
 
 	SUCCEED="true"
+	CSUM=
+	CSUM_FILE=/dev/null
 	for givenfile in $EXTRA_DL_FILES $files ; do
 		f=$(echo $givenfile | sed -e 's#^\./##' -e 's#^/##' -e 's#//#/#g')
 		url="$baseurl/$f"
@@ -414,9 +429,31 @@ fetch_files() {
 
 		[ -e $file.tmp ] && rm $file.tmp
 
-		if [ ! "$OFFLINE" ]; then
+		# Does the checksum of the previous file match the new one?
+		CACHED= #false#
+		SKIP_CSUM= #false#
+		if [ "$givenfile" = "MD5SUMS" ]; then
+			CSUM=md5sum
+			CSUM_FILE="$file.tmp"
+			SKIP_CSUM=true
+		elif [ "$CSUM" ]; then
+			if [ "$OFFLINE" ] || check_sum $givenfile $file; then
+				CACHED=true
+				[ $VERBOSITY -gt 0 ] && echo "I: * $givenfile cached"
+			else
+				[ $VERBOSITY -gt 0 ] && echo "I: * $givenfile not cached"
+			fi
+		fi
+
+		# Download the file, if needed.
+		if [ ! "$OFFLINE" -a ! "$CACHED" ]; then
 			if $GETTER "$file.tmp" -- "$url" ; then
-				fetch_date="$(date -R)"
+				if check_sum $givenfile $file.tmp || [ "$SKIP_CSUM" ] ; then
+					fetch_date="$(date -R)"
+				else
+					echo "E: Checksum verification failed (file $givenfile)." 1>&2
+					exit 1
+				fi
 			else
 				echo "$EXTRA_DL_FILES" | tr " " "\n" | grep -qx $f || SUCCEED="failed"
 				echo "E: Can't download '$release' for '$arch' ($url)." 1>&2
@@ -441,35 +478,11 @@ fetch_files() {
 		fi
 	done
 
-	csum="${DL_CACHE}/$(echo ${repo_loc}/MD5SUMS.tmp | url2filename)"
-	if [ -f "$csum" -a "$SUCCEED" = "true" ] ; then
-		echo -n "I: Computing checksums... "
-		for givenfile in $EXTRA_DL_FILES $files ; do
-			f=$(echo $givenfile | sed -e 's#^\./##' -e 's#^/##' -e 's#//#/#g')
-			file="${DL_CACHE}/$(echo ${repo_loc}/$f | url2filename)"
-			md5=$(md5sum $file.tmp | cut -d " " -f 1)
-			if [ "$givenfile" == "MD5SUMS" ]; then
-				continue
-			fi
-			echo -n "$givenfile "
-			if ! grep -qiE "[[:blank:]]+(\./|)$givenfile[[:blank:]]*$" $csum ; then
-				echo -n " (No checksum)"
-				continue
-			fi
-			if ! grep -qiE "^$md5[[:blank:]]+(\./|)$givenfile[[:blank:]]*$" $csum ; then
-				echo "FAILED"
-				echo "E: Checksum verification failed (the file got corrupted somewhere)." 1>&2
-				SUCCEED="failed"
-				break
-			fi
-		done
-		[ "$SUCCEED" = "true" ] && echo "... done." 1>&2
-
-	elif [ "$SUCCEED" = "true" ]; then
+	if [ ! "$CSUM" ]; then
 		echo "I: No checksum found."
 	fi
 
-
+	# 
 	if [ ! "$OFFLINE" ]; then
 		echo "I: Moving/Removing temporary files."
 		for givenfile in $EXTRA_DL_FILES $files ; do
@@ -729,6 +742,7 @@ install_repo() {
 }
 
 
+VERBOSITY=0
 WGET_VERBOSITY="--quiet"
 CURL_VERBOSITY="--silent"
 RM_VERBOSITY=
@@ -782,6 +796,7 @@ for option in "$@"; do
 	MV_VERBOSITY="-v"
 	CP_VERBOSITY="-v"
 	TAR_VERBOSITY="-v"
+	VERBOSITY=1
 	;;
     --debug)
 	# This is an undocumented feature...
