Improve changelog message
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@47875 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/finish-install/finish-install.d/90console b/packages/finish-install/finish-install.d/90console
--- a/packages/finish-install/finish-install.d/90console
+++ b/packages/finish-install/finish-install.d/90console
@@ -16,7 +16,7 @@ rawconsole=${rawconsole#/dev/}
 console=${console#/dev/}
 
 case "$console" in
-    tty[A-Z]*|hvc*|hvsi*)
+    tty[A-Z]*)
 	log "Configuring init for serial console"
 	consoletype=${console%%[0-9]*}
 	ttyline=${console#$consoletype}
@@ -45,3 +45,43 @@ case "$console" in
 	fi
 	;;
 esac
+
+# Set up virtualized console via onboard service processor (hvsi/hvc)
+
+DT_ROOT=/proc/device-tree
+if [ -e $DT_ROOT/options/chosen/linux,stdout-path ]; then
+	OD=$(cat $DT_ROOT/chosen/linux,stdout-path)
+	case $OD in
+	    /vdevice/vty@30000000)
+		case $(cat ${DT_ROOT}${OD}/compatible) in
+		    hvterm-protocol)
+			console=hvsi0 ;;
+		    hvterm|hvterm1)
+			console=hvc0 ;;
+		    *)
+			log "Unable to determine type of virtualized console"
+			exit 1
+			;;
+		esac
+		;;
+	    /vdevice/vty@30000001)
+		console=hvsi1 ;;
+	    *)
+       		 exit 0 ;;
+	esac
+
+	log "Setting up virtualized serial console on /dev/$console"
+	if [ -f /target/etc/inittab ]; then
+		# Disable regular VTs
+		sed -i -e "s/^\([1-6]\):/#\1:/" /target/etc/inittab
+	
+		console_line="co:2345:respawn:/sbin/getty $console 9600 vt100"
+		if grep -q "^#\?co:" /target/etc/inittab; then
+			sed -i -e "s|^#\?co:.*$|$console_line|" \
+				/target/etc/inittab
+		else
+			sedexp="/^#1:/i\\$console_line\\"
+			sed -i -e "$sedexp" /target/etc/inittab
+		fi
+	fi
+fi
