* Add a facility to install a few extra packages in addition to tasks by   preseeding pkgsel/include.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@39388 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/pkgsel/debian/postinst b/packages/pkgsel/debian/postinst
--- a/packages/pkgsel/debian/postinst
+++ b/packages/pkgsel/debian/postinst
@@ -48,9 +48,16 @@ if in-target sh -c "$config debconf-apt-progress --from 1 --to 5 --logstderr -- 
 	fi
 fi
 
+db_get pkgsel/include
+if [ "$RET" ]; then
+	tasksel_end=90
+else
+	tasksel_end=95
+fi
+
 db_progress INFO pkgsel/progress/tasksel
 ret=0
-in-target sh -c "$config tasksel --new-install --debconf-apt-progress='--from 5 --to 95 --logstderr'" || ret=$?
+in-target sh -c "$config tasksel --new-install --debconf-apt-progress='--from 5 --to $tasksel_end --logstderr'" || ret=$?
 if [ "$ret" != 0 ]; then
 	# In case packages failed to install, try to clean up.
 	in-target dpkg --configure -a || true
@@ -62,6 +69,26 @@ if [ "$ret" != 0 ]; then
 	fi
 	db_progress STOP
 	exit $ret
+fi
+
+db_get pkgsel/include
+if [ "$RET" ]; then
+	# Allow comma-separation so that this can more easily be preseeded
+	# at the kernel command line.
+	RET="$(printf '%s' "$RET" | sed 's/,/ /g')"
+	in-target sh -c "$config debconf-apt-progress --from 90 --to 95 --logstderr -- aptitude -q --without-recommends -y install $RET" || ret=$?
+	if [ "$ret" != 0 ]; then
+		# In case packages failed to install, try to clean up.
+		in-target dpkg --configure -a || true
+
+		# TODO useful error message here (for ret != 30)
+		db_progress INFO pkgsel/progress/cleanup
+		if ! cleanup; then
+			log "cleanup failed"
+		fi
+		db_progress STOP
+		exit $ret
+	fi
 fi
 
 db_progress INFO pkgsel/progress/cleanup
