* Run dpkg --configure -a if tasksel fails to avoid leaving the system   with packages in an unconfigured state and breaking pkgsel re-runs.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@33333 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/pkgsel/debian/postinst b/packages/pkgsel/debian/postinst
--- a/packages/pkgsel/debian/postinst
+++ b/packages/pkgsel/debian/postinst
@@ -64,6 +64,9 @@ db_progress INFO pkgsel/progress/tasksel
 ret=0
 in-target sh -c "$config tasksel --new-install --debconf-apt-progress='--from 15 --to 95 --logstderr'" || ret=$?
 if [ "$ret" != 0 ]; then
+	# In case packages failed to install, try to clean up.
+	in-target dpkg --configure -a || true
+	
 	# TODO useful error message here (for ret != 30)
 	db_progress INFO pkgsel/progress/cleanup
 	cleanup
