* Add a facility to disable installation of popularity-contest by     preseeding popularity-contest/participate to false.   * Add a facility to disable tasksel run by preseeding tasksel/first to     an empty string.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@39721 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/pkgsel/debian/postinst b/packages/pkgsel/debian/postinst
--- a/packages/pkgsel/debian/postinst
+++ b/packages/pkgsel/debian/postinst
@@ -40,35 +40,48 @@ config=$(chroot /target debconf-apt-progress --config| sed "s/$/;/")
 
 db_progress STEP 1
 
-# Install popularity-contest but remove it if the user decides not to
-# participate.
-if in-target sh -c "$config debconf-apt-progress --from 1 --to 5 --logstderr -- apt-get -q -y -f install popularity-contest"; then
-	if ! grep -q '^PARTICIPATE=\"*yes\"*' /target/etc/popularity-contest.conf; then
-		in-target dpkg --purge popularity-contest
+# progressbar should start at 1
+progress_start=1
+
+if ! db_get popularity-contest/participate || [ "$RET" != false ]; then
+	progress_end=5
+	# Install popularity-contest but remove it if the user decides not to
+	# participate.
+	if in-target sh -c "$config debconf-apt-progress --from $progress_start --to $progress_end --logstderr -- apt-get -q -y -f install popularity-contest"; then
+		if ! grep -q '^PARTICIPATE=\"*yes\"*' /target/etc/popularity-contest.conf; then
+			in-target dpkg --purge popularity-contest
+		fi
 	fi
+	progress_start=$progress_end
 fi
 
 db_get pkgsel/include
 if [ "$RET" ]; then
-	tasksel_end=90
+	progress_end=90
 else
-	tasksel_end=95
+	progress_end=95
 fi
 
-db_progress INFO pkgsel/progress/tasksel
-ret=0
-in-target sh -c "$config tasksel --new-install --debconf-apt-progress='--from 5 --to $tasksel_end --logstderr'" || ret=$?
-if [ "$ret" != 0 ]; then
-	# In case packages failed to install, try to clean up.
-	in-target dpkg --configure -a || true
-	
-	# TODO useful error message here (for ret != 30)
-	db_progress INFO pkgsel/progress/cleanup
-	if ! cleanup; then
-		log "cleanup failed"
+if ! db_fget tasksel/first seen || (! db_get tasksel/first || [ -z "$RET" ]); then
+	db_progress INFO pkgsel/progress/tasksel
+	ret=0
+	in-target sh -c "$config tasksel --new-install --debconf-apt-progress='--from $progress_start --to $progress_end --logstderr'" || ret=$?
+
+	if [ "$ret" != 0 ]; then
+		# In case packages failed to install, try to clean up.
+		in-target dpkg --configure -a || true
+		
+		# TODO useful error message here (for ret != 30)
+		db_progress INFO pkgsel/progress/cleanup
+		if ! cleanup; then
+			log "cleanup failed"
+		fi
+		db_progress STOP
+		exit $ret
 	fi
-	db_progress STOP
-	exit $ret
+	progress_start=$progress_end
+else
+	progress_end=100
 fi
 
 db_get pkgsel/include
@@ -76,7 +89,7 @@ if [ "$RET" ]; then
 	# Allow comma-separation so that this can more easily be preseeded
 	# at the kernel command line.
 	RET="$(printf '%s' "$RET" | sed 's/,/ /g')"
-	in-target sh -c "$config debconf-apt-progress --from 90 --to 95 --logstderr -- aptitude -q --without-recommends -y install $RET" || ret=$?
+	in-target sh -c "$config debconf-apt-progress --from $progress_start --to $progress_end --logstderr -- aptitude -q --without-recommends -y install $RET" || ret=$?
 	if [ "$ret" != 0 ]; then
 		# In case packages failed to install, try to clean up.
 		in-target dpkg --configure -a || true
