Only mount /target/proc if it's not already mounted (closes: #248102).
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@15049 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/arch/powerpc/yaboot-installer/debian/postinst b/packages/arch/powerpc/yaboot-installer/debian/postinst
--- a/packages/arch/powerpc/yaboot-installer/debian/postinst
+++ b/packages/arch/powerpc/yaboot-installer/debian/postinst
@@ -119,11 +119,13 @@ rootdev="`sed -n -e '/^[^[:space:]]\+[[:space:]]\+\/target[[:space:]]/ { s/[[:sp
 [ "$rootdev" ] || die yaboot-installer/noroot 'No root partition found'
 
 # mkofboot needs proc in /target
-mkdir -p /target/proc || \
-    die yaboot-installer/mounterr 'Error creating /target/proc'
-mount -t proc none /target/proc || \
-    die yaboot-installer/mounterr 'Error mounting /target/proc'
-trap 'umount /target/proc' HUP INT QUIT KILL PIPE TERM EXIT
+if ! [ -e /target/proc/cmdline ]; then
+    mkdir -p /target/proc || \
+	die yaboot-installer/mounterr 'Error creating /target/proc'
+    mount -t proc proc /target/proc || \
+	die yaboot-installer/mounterr 'Error mounting /target/proc'
+    trap 'umount /target/proc' HUP INT QUIT KILL PIPE TERM EXIT
+fi
 
 # Probe for other OSes.
 
