Add Mac OS and Mac OS X to the multiboot menu if os-prober finds them.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@13514 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/arch/powerpc/yaboot-installer/debian/postinst b/packages/arch/powerpc/yaboot-installer/debian/postinst
--- a/packages/arch/powerpc/yaboot-installer/debian/postinst
+++ b/packages/arch/powerpc/yaboot-installer/debian/postinst
@@ -11,12 +11,6 @@ set -e
 
 . /usr/share/debconf/confmodule
 
-if [ -f /etc/mtab ]; then
-    MTAB=/etc/mtab
-else
-    MTAB=/proc/mounts
-fi
-
 log() {
     logger -t yaboot-installer "$@"
 }
@@ -29,7 +23,7 @@ info() {
     log "info: $@"
 }
 
-db_progress START 0 5 yaboot-installer/progress
+db_progress START 0 6 yaboot-installer/progress
 
 die() {
     template="$1"
@@ -110,6 +104,38 @@ mount -t proc none /target/proc || \
     die yaboot-installer/mounterr 'Error mounting /target/proc'
 trap 'umount /target/proc' HUP INT QUIT KILL PIPE TERM EXIT
 
+# Probe for other OSes.
+
+db_progress STEP 1
+db_progress INFO yaboot-installer/os-probing
+
+newline="
+"
+
+probed="$(os-prober)"
+
+if [ "$probed" ]; then
+    OLDIFS="$IFS"
+    IFS="$newline"
+    for os in $probed; do
+	IFS="$OLDIFS"
+	info "probed: $os"
+	partition="$(echo "$os" | cut -d: -f1)"
+	mappedpartition="$(mapdevfs "$partition")"
+	label="$(echo "$os" | cut -d: -f3)"
+	loadertype="$(echo "$os" | cut -d: -f4)"
+	# You only get the first of each non-Linux OS here, as that's all
+	# yaboot supports without painful hacking. Sorry.
+	case $loadertype in
+	    macosx)	[ "$macosx" ] || macosx="$mappedpartition" ;;
+	    macos)	[ "$macos" ]  || macos="$mappedpartition"  ;;
+	    *)		info "unhandled: $os" ;;
+	esac
+	IFS="$newline"
+    done
+    IFS="$OLDIFS"
+fi
+
 # Generate yaboot.conf
 
 db_progress STEP 1
@@ -126,8 +152,15 @@ ofpath="`chroot /target /usr/sbin/ofpath "$disk"`"
 # we generate our own yaboot.conf kernel (yabootconfig is horribly broken)
 # cjwatson: a little more justification of that would have been nice ...
 
-cat >/target/etc/yaboot.conf \
-    <<EOF || die yaboot-installer/conferr 'Error writing to yaboot.conf'
+>/target/etc/yaboot.conf \
+    || die yaboot-installer/conferr 'Error writing to yaboot.conf'
+
+writeyabootconf () {
+    cat >>/target/etc/yaboot.conf \
+	|| die yaboot-installer/conferr 'Error writing to yaboot.conf'
+}
+
+writeyabootconf <<EOF
 ## yaboot.conf generated by debian-installer
 ##
 ## run: "man yaboot.conf" for details. Do not make changes until you have!!
@@ -143,6 +176,17 @@ root=$root
 timeout=30
 install=/usr/lib/yaboot/yaboot
 magicboot=/usr/lib/yaboot/ofboot
+enablecdboot
+EOF
+
+if [ "$macos" ]; then
+    echo "macos=$macos" | writeyabootconf
+fi
+if [ "$macosx" ]; then
+    echo "macosx=$macosx" | writeyabootconf
+fi
+
+writeyabootconf <<EOF
 
 image=/vmlinux
 	label=linux
@@ -151,9 +195,6 @@ image=/vmlinux
 image=/vmlinux.old
 	label=old
 	read-only
-
-enablecdboot
-
 EOF
 
 # Install into bootstrap partition
