* Make the menu item to run before partman, depend on configured-network,   and run rdate to pull time from NTP, as well as running tzsetup.   Closes: #236673, #247484 * Move the UTC question into the finish-install script. * Use hwclock to store the correct time to the system clock at the end of   the install. * Since hwclock has been known to hang on problimatic hardware, deal with   hangs. * Add support for using the rtc-dev driver on the nslu2. * Remove old isinstallable file that was for sarge, we don't support sarge   installs anymore. * Make whether to use NTP, as well as the server to use be asked as low   priority questions, and preseedable.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@48620 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/clock-setup/debian/clock-setup.postinst b/packages/clock-setup/debian/clock-setup.postinst
--- a/packages/clock-setup/debian/clock-setup.postinst
+++ b/packages/clock-setup/debian/clock-setup.postinst
@@ -3,48 +3,31 @@ set -e
 
 . /usr/share/debconf/confmodule
 
-db_progress START 0 1 clock-setup/progress/title
-db_progress INFO clock-setup/progress/working
-
-os_needs_local_clock () {
-	while read line; do
-		shortname=$(echo "$line" | cut -d : -f 3)
-		case $shortname in
-		MS-DOS*|Windows*|FreeDOS*) # keep in sync with os-prober
-			return 0
-		;;
-		esac
-	done
-	return 1
+log() {
+	logger -t clock-setup "$@"
 }
 
-pri=high
-
-if db_fget clock-setup/utc seen && [ "$RET" = true ]; then
-	# keep preseeded value
-	:
-else
-	probed=$(os-prober)
-
-	if echo "$probed" | os_needs_local_clock; then
-		# default to localtime for some OSes
-		db_set clock-setup/utc false
-		pri=low
-	fi
-
-	if [ -z "$probed" ]; then
-		# installing the only OS, so use UTC
-		db_set clock-setup/utc true
-		pri=low
-	fi
-fi
-
-db_progress STEP 1
-
-db_input $pri clock-setup/utc || true
+db_input medium clock-setup/ntp || true
 if ! db_go; then
-	db_progress stop
 	exit 10 # back to main menu
 fi
+db_get clock-setup/ntp
+if [ "$RET" = true ]; then
+	db_input low clock-setup/ntp-server || true
+	if ! db_go; then
+		exit 10
+	fi
+	db_get clock-setup/ntp-server
+	server="$RET"
 
-db_progress stop
+	db_progress START 0 1 clock-setup/progress/title
+	db_progress INFO clock-setup/progress/ntp
+	if ! RDATE_OUT=`log-output -t clock-setup --pass-stdout rdate -o 123 -nv "$server"`; then
+		log "rdate failed ($?)"
+	fi
+	log "$RDATE_OUT"
+	db_progress step 1
+	db_progress stop
+fi
+
+tzsetup
diff --git a/packages/clock-setup/finish-install.d/10clock-setup b/packages/clock-setup/finish-install.d/10clock-setup
--- a/packages/clock-setup/finish-install.d/10clock-setup
+++ b/packages/clock-setup/finish-install.d/10clock-setup
@@ -3,6 +3,54 @@ set -e
 
 . /usr/share/debconf/confmodule
 
+log() {
+	logger -t clock-setup "$@"
+}
+warning() {
+	log "warning: $*"
+}
+
+os_needs_local_clock () {
+	while read line; do
+		shortname=$(echo "$line" | cut -d : -f 3)
+		case $shortname in
+		MS-DOS*|Windows*|FreeDOS*) # keep in sync with os-prober
+			return 0
+		;;
+		esac
+	done
+	return 1
+}
+
+pri=high
+
+if db_fget clock-setup/utc seen && [ "$RET" = true ]; then
+	# keep preseeded value
+	:
+else
+	# os-prober is may not yet be installed..
+	anna-install os-prober || true
+
+	probed=$(os-prober)
+
+	if echo "$probed" | os_needs_local_clock; then
+		# default to localtime for some OSes
+		db_set clock-setup/utc false
+		pri=low
+	fi
+
+	if [ -z "$probed" ]; then
+		# installing the only OS, so use UTC
+		db_set clock-setup/utc true
+		pri=low
+	fi
+fi
+
+db_input $pri clock-setup/utc || true
+if ! db_go; then
+	exit 10 # back to main menu
+fi
+
 rcsfile=/target/etc/default/rcS
 adjtimefile=/target/etc/adjtime
 
@@ -14,3 +62,73 @@ else
 	sed -i -e 's:^UTC="yes":UTC="no":' -e 's:^UTC=yes:UTC=no:' $rcsfile
 	sed -i -e 's:^UTC:LOCAL:' $adjtimefile
 fi
+
+anna-install rtc-modules || true
+machine=$(grep "^Hardware" /proc/cpuinfo | sed 's/Hardware\s*:\s*//')
+case "$machine" in
+	"Linksys NSLU2")
+		# The nslu2 needs a special driver for the hardware
+		# clock.
+		log-output -t hw-detect modprobe -v rtc-dev || log "rtc-dev failed to load"
+		update-dev
+		# This driver creates a rtc0 device, so symlink.
+		if [ -e /dev/rtc0 ]; then
+			ln -sf rtc0 /dev/rtc
+		fi
+	;;
+	*)
+		# This may not be necessary; hwclock can do direct IO if
+		# the rtc module is not loaded.
+		log-output -t hw-detect modprobe -v rtc || log "rtc failed to load"
+		update-dev
+	;;
+esac
+
+# bind mount /dev into /target/dev so that rtc devices are available for hwclock
+if mount -o bind /dev /target/dev; then
+	target_dev_mounted=1
+else
+	warning "failed to bind mount /target/dev"
+fi
+
+cleanup () {
+	if [ "$target_dev_mounted" ] && ! umount /target/dev; then
+		warning "failed to unmount /target/dev bind mount"
+	fi
+}
+
+db_progress INFO clock-setup/progress/hwclock
+log-output -t clock-setup chroot /target hwclock --systohc --debug &
+pid="$!"
+count=0
+
+stop_hwclock () {
+	kill $pid || return
+	sleep 1
+	if [ -e /proc/$pid ]; then
+		kill -9 $pid || return
+	fi
+}
+
+while sleep 1; do
+	if [ ! -e /proc/$pid ]; then
+		break
+	fi
+	count=$(expr $count + 1)
+	if [ "$count" = 30 ]; then
+		count=0
+		db_input critical clock-setup/hwclock-wait || true
+		if ! db_go; then
+			stop_hwclock
+			cleanup
+			exit 10 # back to main menu
+		fi
+		db_get clock-setup/hwclock-wait
+		if [ "$RET" = false ]; then
+			stop_hwclock
+			break
+		fi
+	fi
+done
+
+cleanup
