Map DevFS-style pathnames to static ones, so that vmelilo-installer works correctly on 2.4, too.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@28064 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/arch/m68k/vmelilo-installer/debian/postinst b/packages/arch/m68k/vmelilo-installer/debian/postinst
--- a/packages/arch/m68k/vmelilo-installer/debian/postinst
+++ b/packages/arch/m68k/vmelilo-installer/debian/postinst
@@ -36,6 +36,12 @@ findfs () {
 
 write_conf () {
 
+    case $BOOTDEV in
+        /dev/scsi*)
+	  BOOTDEV=$(mapdevfs $BOOTDEV)
+	  ROOTDEV=$(mapdevfs $ROOTDEV)
+	;;
+    esac
     cat > /target/etc/vmelilo.conf << EOF || die vmelilo-installer/conferr "Error writing /target/etc/vmelilo.conf"
 
 ## vmelilo.conf generated by debian-installer
@@ -67,7 +73,16 @@ write_bootblock () {
             ;;
     esac
     
-    LD_LIBRARY_PATH=\"/target/lib:/target/usr/lib\" /target/sbin/vmelilo -f -w /target || die vmelilo-installer/booterr "Error writing vmelilo"
+    case $(uname -r) in
+      2.2*)
+    	LD_LIBRARY_PATH=\"/target/lib:/target/usr/lib\" /target/sbin/vmelilo -f -w /target || die vmelilo-installer/booterr "Error writing vmelilo"
+	;;
+      2.4*)
+        mount -t proc proc /target/proc
+        chroot /target /sbin/vmelilo -f || die vmelilo-installer/booterr "Error writing vmelilo"
+	umount /target/proc
+	;;
+    esac
 }
 
 
