* Use log-output in vmelilo call.   * Removed the LD_LIBRARY_PATH stuff for 2.2, use code now tested for 2.4 in     all cases.   * Template update due to logging changes.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@30738 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/arch/m68k/vmelilo-installer/debian/postinst b/packages/arch/m68k/vmelilo-installer/debian/postinst
--- a/packages/arch/m68k/vmelilo-installer/debian/postinst
+++ b/packages/arch/m68k/vmelilo-installer/debian/postinst
@@ -73,16 +73,9 @@ write_bootblock () {
             ;;
     esac
     
-    case $(uname -r) in
-      2.2*)
-    	LD_LIBRARY_PATH=\"/target/lib:/target/usr/lib\" /target/sbin/vmelilo -f -w /target || die vmelilo-installer/booterr "Error writing vmelilo"
-	;;
-      2.4*)
-        mount -t proc proc /target/proc
-        chroot /target /sbin/vmelilo -f || die vmelilo-installer/booterr "Error writing vmelilo"
-	umount /target/proc
-	;;
-    esac
+    mount -t proc proc /target/proc
+    log-output vmelilo-installer chroot /target /sbin/vmelilo -f || die vmelilo-installer/booterr "Error writing vmelilo"
+    umount /target/proc
 }
 
 
