Lots of changes to make cdebconf more debconf-compatible; the frontend and database modules are broken at the moment; will be fixed shortly
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@726 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/cdebconf/configure.in b/tools/cdebconf/configure.in
--- a/tools/cdebconf/configure.in
+++ b/tools/cdebconf/configure.in
@@ -1,4 +1,3 @@
-
 dnl Process this file with autoconf to produce a configure script.
 dnl The ONLY thing this is used for is to configure for different
 dnl linux architectures and configurations, it is not used to make the
@@ -17,9 +16,14 @@ AC_PROG_MAKE_SET
 AC_PROG_CC
 AC_ISC_POSIX
 
+dnl We must have sed...
 AC_CHECK_PROG(HAVESED,sed,yes,no)
-
 test "$HAVESED" = "yes" || exit 1
+
+dnl Use pod2man for generating manpages
+AC_PATH_PROG(POD2MAN,pod2man)
+test -n "$POD2MAN" || exit 1
+AC_SUBST(POD2MAN)
 
 dnl setup source and build paths
 TOPDIR=$(dirname $0)
@@ -32,14 +36,8 @@ BUILDDIR=$(pwd)
 AC_SUBST(BUILDDIR)
 
 if [[ "$TOPDIR" != "$BUILDDIR" ]]; then
-	echo "Symlinking source tree..."
-	for f in $(find "$TOPDIR" -path "$BUILDDIR" -prune -o -path "*CVS*" -prune \
-			-o -type f -print);
-	do
-		destdir=$(dirname $(echo $f | sed -e "s,$TOPDIR,$BUILDDIR,"))
-		[[ -d $destdir ]] || mkdir -p $destdir
-		[[ -e $destdir/$(basename $f) ]] || ln -s $f $destdir
-	done
+	echo "Setting up build directory"
+    cp $TOPDIR/Makefile $BUILDDIR
 fi
 
 dnl Enable debugging?
@@ -58,22 +56,11 @@ fi
 
 dnl What db modules to build?
 AC_ARG_WITH(db,[  --with-db               db modules to build])
-if test -n "$with_db"; then
-  DBMODULES=$with_db
-else
-  DBMODULES="rfc822db textdb perldb"
-fi
-AC_SUBST(DBMODULES)
+DB_MODULES=$with_db
 
 dnl What frontend modules to build?
 AC_ARG_WITH(frontend,[  --with-frontend         frontend modules to build])
-if test -n "$with_frontend"; then
-  FRONTENDMODULES="$with_frontend"
-else
-  FRONTENDMODULES="text slang"
-fi
-AC_SUBST(FRONTENDMODULES)
-
+FRONTEND_MODULES=$with_frontend
 
 dnl debconf config file
 DEBCONFCONFIG="/etc/cdebconf.conf"
@@ -87,18 +74,29 @@ AC_DEFINE_UNQUOTED(DEBCONFCONFIG, "$DEBCONFCONFIG")
 dnl Check for libraries
 AC_CHECK_LIB(dl, dlopen)
 
+dnl Autodetect what to build if not specified
+
+dnl Databases - which to include.
+if test -z "$DB_MODULES"; then
+    DB_MODULES="textdb rfc822db"
+
+    AC_CHECK_LIB(mysqlclient, mysql_init, DB_MODULES="$DB_MODULES mysql", echo "*** Cannot build mysql database ***")
+fi
+
 dnl Frontends - which to include.
 
-FRONTEND_MODULES=text
+if test -z "$FRONTEND_MODULES"; then
+    FRONTEND_MODULES=text
 
-AC_CHECK_LIB(ncurses, initscr, FRONTEND_MODULES="$FRONTEND_MODULES ncurses",
- echo "*** Cannot build ncurses frontend ***")
-AC_CHECK_LIB(bogl, bowl_flush, FRONTEND_MODULES="$FRONTEND_MODULES bogl",
- echo "*** Cannot build BOGL frontend ***")
-AC_CHECK_LIB(slang, SLang_init_all, FRONTEND_MODULES="$FRONTEND_MODULES slang",
- echo "*** Cannot build SLang frontend ***")
+    AC_CHECK_LIB(ncurses, initscr, FRONTEND_MODULES="$FRONTEND_MODULES ncurses", echo "*** Cannot build ncurses frontend ***")
+    AC_CHECK_LIB(bogl, bowl_flush, FRONTEND_MODULES="$FRONTEND_MODULES bogl", echo "*** Cannot build BOGL frontend ***")
+    AC_CHECK_LIB(slang, SLang_init_all, FRONTEND_MODULES="$FRONTEND_MODULES slang", echo "*** Cannot build SLang frontend ***")
+
+    AC_SUBST(FRONTEND_MODULES)
+fi
 
 AC_SUBST(FRONTEND_MODULES)
+AC_SUBST(DB_MODULES)
 
 dnl Checks for header files.
 AC_HEADER_DIRENT
@@ -122,4 +120,4 @@ AC_PROG_GCC_TRADITIONAL
 AC_TYPE_SIGNAL
 AC_CHECK_FUNCS(socket strdup strstr strtol)
 
-AC_OUTPUT(globalmakeflags src/makefile)
+AC_OUTPUT(globalmakeflags src/Makefile man/Makefile)
