bochs support code
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@23028 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/digress/test-harness b/scripts/digress/test-harness
--- a/scripts/digress/test-harness
+++ b/scripts/digress/test-harness
@@ -31,9 +31,11 @@ endheader () {
 
 do_shutdown () {
 	if [ -n "$SHUTDOWN" ]; then
-		if ! $SHUTDOWN; then
-			echo "SHUTDOWN $SHUTDOWN failed"
-		fi
+		for t in $SHUTDOWN; do
+			if ! $t; then
+				echo "SHUTDOWN $t failed"
+			fi
+		done
 	fi
 }
 
