support multiple boot scripts break up ia64-serial-boot
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@22258 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/digress/test-harness b/scripts/digress/test-harness
--- a/scripts/digress/test-harness
+++ b/scripts/digress/test-harness
@@ -124,9 +124,12 @@ endheader
 if [ -n "$BOOT" ]; then
 	echo
 	header "Booting..."
-	if ! $BOOT; then
-		error "BOOT $BOOT failed"
-	fi
+	endheader
+	for t in $BOOT; do
+		if ! $t; then
+			error "BOOT $t failed"
+		fi
+	done
 fi
 
 if [ -n "$TEST_1" ]; then
