- Move countrychooser into the postinst.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@7945 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/countrychooser/debian/postinst b/tools/countrychooser/debian/postinst
--- a/tools/countrychooser/debian/postinst
+++ b/tools/countrychooser/debian/postinst
@@ -1,11 +1,106 @@
-#!/bin/sh -e
+#!/bin/sh
+set -e
 
-PATH=$PATH:.
+. /usr/share/debconf/confmodule
 
-# Enable translations (if this is present, base-config generated the
-# required locale on boot)
+localecode="debian-installer/locale"
+languagecode="debian-installer/language"
+countrycode="debian-installer/country"
 
-countrychooser
-#DEBHELPER#
+log() {
+    logger -t countrychooser "info: $@"
+}
+
+for list in /etc/iso_3166.tab ; do 
+    if [ -f "$list" ] ; then
+	countries="$list"
+    fi
+done
+
+countrycodemap() {
+line=`grep "$COUNTRYCODE" $countries`
+
+if [ "$line" ] ; then
+    # Remember that country names may have spaces so the code
+    # here different than countrymap
+    COUNTRYNAME=`echo $line|cut -b 4-`
+else
+    echo "error: Unable to locate info on country '$COUNTRYCODE'"
+fi
+}
+
+countrymap() {
+line=`grep "$COUNTRYNAME" $countries`
+
+if [ "$line" ] ; then
+    set $line
+
+    if [ "$1" ] ; then COUNTRYCODE="$1"; fi
+
+else
+    echo "error: Unable to locate info on country '$COUNTRYNAME'"
+fi
+}
+
+
+# First grab back the country we got from languagechooser
+# (or from elsewhere)
+# and populate the debconf database with it so that it becomes
+# the default choice
+db_get "$countrycode"
+if test "$RET" ; then
+  COUNTRYCODE="$RET"
+  countrycodemap
+  db_set "countrychooser/country-name" "$COUNTRYNAME"
+fi
+
+# Remember which code was first used
+COUNTRYCODE_LANGUAGECHOOSER=$COUNTRYCODE
+
+db_input critical "countrychooser/country-name" || [ $? -eq 30 ]
+if db_go; then
+    db_get "countrychooser/country-name"
+    if test "$RET" ; then
+	COUNTRYNAME="$RET"
+	countrymap
+	db_set "$countrycode"  "$COUNTRYCODE"
+	db_get "$languagecode"
+	if test "$RET" ; then
+	    LANGUAGECODE=$RET
+	    # Locale setting
+	    # Keep locale inherited from languagechooser
+	    # if the country wasn't changed
+	    # Otherwise, add "language_COUNTRY" to the original locale
+	    # This allows keeping the fallback values
+	    # Make sure locale is at least "C"
+	    if [ "$LANGUAGECODE" != "C" ]
+	    then
+		db_get "$localecode"
+		if test "$RET" ; then
+		    LOCALE="$RET"
+		else
+		    LOCALE="C"
+		fi
+ 	        if [ "$COUNTRYCODE" != "$COUNTRYCODE_LANGUAGECHOOSER" ] ; then
+			LOCALE=${LANGUAGECODE}_${COUNTRYCODE}:${LOCALE}
+		fi
+	    else
+		LOCALE=C
+	    fi
+	else
+	    LOCALE=C
+	fi
+	db_set "$localecode"   "$LOCALE"
+    else
+	# Error, not sure how to handle it
+	:
+    fi
+else
+    # Error, not sure how to handle it
+    :
+fi
+
+log "$countrycode   = '$COUNTRYCODE'"
+log "$localecode  = '$LOCALE'"
 
 exit 0
