- No need to apt-install discover; hw-detect does that.     - Cleaned up the prompting if the CD device is found and CD is not       auto-mounted. Closes: #213174     - Remove dangling skip-autodetection template.     - Don't give up on a non-debian CD until all drives have been scanned,       and allow the user to insert the right CD to continue.     - Fix debian/rules to use binary-indep, not -arch. Closes: #223087     - Update to debhelper v4.     - Clean up rules file.     - Remove Standards-Version; it's a udeb.     - Remove the mtab hack in the prebaseconfig hack, /etc/mtab is a link to       /proc/mounts in the rootskel.     - Fix prebaseocnfig script to eject the right cdrom, by calling eject on       /cdrom. No more coffee spills.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@7540 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/cdrom-detect/debian/cdrom-detect.postinst b/tools/cdrom-detect/debian/cdrom-detect.postinst
--- a/tools/cdrom-detect/debian/cdrom-detect.postinst
+++ b/tools/cdrom-detect/debian/cdrom-detect.postinst
@@ -8,6 +8,13 @@ log() {
     logger -t cdrom-detect "$@"
 }
 
+fail () {
+    log "CDROM-detect failed."
+    db_input critical cdrom-detect/failure || [ $? -eq 30 ]
+    db_go
+    exit 1
+}
+
 # Is a cdrom already mounted?  If so, assume it's the right one..
 mount | grep -q ^/dev/cdroms/ && exit 0
 
@@ -22,10 +29,6 @@ while true
 do
     mounted=0
 
-    # What about ISA cdroms ?
-    # discover doesn't do devfs, :/
-
-    # devices=`/sbin/discover --disable-all --enable=pci,ide,scsi --device cdrom`
     if [ -d /dev/cdroms ]; then
         devices="`echo /dev/cdroms/*`"
     else
@@ -45,16 +48,18 @@ do
         break
     fi
 
-    # If device was detect but mount failed, ask for inserting the CD
+    # If a device was detected but the mount failed, ask for the CD.
     if [ -n "$devices" ]
     then
-	db_fset cdrom-detect/is_cd_inserted seen false
-	db_input critical cdrom-detect/is_cd_inserted || [ $? -eq 30 ]
+	db_fset cdrom-detect/retry seen false
+	db_input critical cdrom-detect/retry || [ $? -eq 30 ]
 	db_go
-	db_get cdrom-detect/is_cd_inserted
-	if [ "$RET" = "false" ]
+	db_get cdrom-detect/retry
+	if [ "$RET" = "true" ]
 	then
 	    continue
+	else
+            fail
 	fi
     fi
     
@@ -69,9 +74,6 @@ do
     do
 	modules="$modules, $i"
     done
-    
-    # Here's the list of device
-    # UPDATE IT HERE if you want to add some devices
     
     if [ "$RET" = "true" ]
     then
@@ -100,10 +102,7 @@ do
 	    break
 	fi
     else
-	log "CDROM-detect failed."
-	db_input critical cdrom-detect/no-cd || [ $? -eq 30 ]
-	db_go
-	exit 1
+	fail
     fi
 done
 
@@ -130,11 +129,6 @@ done
 # Ask for eject to be installed into /target/, to be able to use it in
 # the prebaseconfig script.
 apt-install eject || true
-
-# Ask for discover to be installed into /target/, to make sure the
-# required drivers are loaded when base-config is looking for the
-# install CD
-apt-install discover || true
 
 # Hey, we're done
 db_fset cdrom-detect/success seen false
