Add check for needed commands
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@51049 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/kernel/massbuild b/packages/kernel/massbuild
--- a/packages/kernel/massbuild
+++ b/packages/kernel/massbuild
@@ -155,6 +155,14 @@ for arch in $ARCHES; do
 	fi
 done
 
+# Check that needed commands are available
+for cmd in kernel-wedge fakeroot; do
+	if ! type kernel-wedge >/dev/null; then
+		echo "Error: command '$cmd' is not available"
+		exit 1
+	fi
+done
+
 CL_TEMP="$(mktemp -t massbuild.changelog.XXXXXX)"
 trap 'rm -f "$CL_TEMP"' EXIT HUP INT QUIT TERM
 
