Try downloads three times before prompting the user (closes: #260348).
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@18066 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/retriever/net/net-retriever b/packages/retriever/net/net-retriever
--- a/packages/retriever/net/net-retriever
+++ b/packages/retriever/net/net-retriever
@@ -20,19 +20,23 @@ fi
 
 fetch() {
     url="${protocol}://${hostname}${directory}/$1"
-    if [ ! -e "$2" ]; then
-      wget -q "$url" -O "$2"
-      return $?
-    else
-      # busybox wget can sometimes become confused while resuming,
-      # so it it fails, restart
-      if wget -c -q "$url" -O "$2"; then
-        return 0
-      else
-	wget -q "$url" -O "$2"
-	return $?
-      fi
-    fi
+    iters=0
+    while [ $iters -lt 3 ]; do
+	if [ ! -e "$2" ]; then
+	    wget -q "$url" -O "$2"
+	    return $?
+	else
+            # busybox wget can sometimes become confused while resuming,
+            # so if it fails, restart
+	    if wget -c -q "$url" -O "$2"; then
+		return 0
+	    else
+		wget -q "$url" -O "$2"
+		return $?
+	    fi
+	fi
+	iters=$(($iters + 1))
+    done
 }
 
 cmd="$1"
