initial support for qemu in mips
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@45975 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/digress/shutdown/cleanupqemu b/scripts/digress/shutdown/cleanupqemu
--- a/scripts/digress/shutdown/cleanupqemu
+++ b/scripts/digress/shutdown/cleanupqemu
@@ -1,3 +1,7 @@
 #!/bin/sh
 set -e
-rm -f $STATE_DIR/qemu-$MACHINE-$SCHEME.*
+if [ -z "$STATE_DIR" ] || [ -z "$MACHINE" ] || [ -z "$SCHEME" ]; then
+	echo "cleanupqemu: error!" >&2
+	exit 1
+fi
+rm -rf "$STATE_DIR/qemu-$MACHINE-$SCHEME".*
