Require parameter
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@48019 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/generate-modules-list b/scripts/generate-modules-list
--- a/scripts/generate-modules-list
+++ b/scripts/generate-modules-list
@@ -2,6 +2,12 @@
 # Generates a list of all modules included in any of the d-i kernel udebs.
 # The parameter is the directory that contains the source for kernel-wedge
 # and all the packages. This is to be used in discover-data reduction.
+
+if [ -z "$1" ]; then
+	echo "Missing required parameter (kernel udebs base directory)"
+	exit 1
+fi
+
 (
 	for dir in $1/*; do
 		if [ -d "$dir" ]; then
