- Add option to specify one or more paths on the command line - Better check for more than one UNRELEASED entry - Better separation of changelogs for different packages in output
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@49210 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/list-unreleased b/scripts/list-unreleased
--- a/scripts/list-unreleased
+++ b/scripts/list-unreleased
@@ -1,10 +1,10 @@
 #!/bin/bash
 
-# Script searches for components with pending changes (UNRELEASED) and
+# Script searches for packages with pending changes (UNRELEASED) and
 # either lists them or displays the relevant changelog entry.
 
 # Usage: list-unreleased [-c]
-#        -c display pending changes
+#        -c : display pending changes
 
 # Copyright: Frans Pop <elendil@planet.nl>, 2007
 # This program is free software; you can redistribute it and/or modify it
@@ -12,27 +12,70 @@
 # Software Foundation; either version 2 of the License, or (at your option)
 # any later version.
 
+PATHS=""
+DO_CL=""
+
+while true; do
+	case "$1" in
+	    "")
+		break ;;
+	    -c)
+		DO_CL=1
+		;;
+	    -*)
+		echo "unrecognized argument '$1'"
+		exit 1
+		;;
+	    *)
+		# Strip trailing slash
+		PATHS="${PATHS:+$PATHS }$1"
+		;;
+	esac
+	shift
+done
+
+[ "$PATHS" ] || PATHS=.
+
 get_list() {
-	for dir in $(find . -type d); do
+	local path="$1"
+
+	for dir in $(find "$path" -type d | grep -v "\.svn"); do
 		changelog="$dir/debian/changelog"
-		if [ -f $changelog ] ; then
-			if head -n1 $changelog | grep -q UNRELEASED; then
-				echo $dir | sed "s:^\./::"
+		if [ -f "$changelog" ] ; then
+			if head -n1 "$changelog" | grep -q UNRELEASED; then
+				echo $dir
 			fi
 		fi
 	done | sort
 }
 
-if [ "$1" = -c ]; then
-	for component in $(get_list); do
-		echo "$component:"
-		changelog="./$component/debian/changelog"
-		if [ $(grep -c UNRELEASED $changelog) -gt 1 ]; then
-			echo "WARNING: changelog has more than one UNRELEASED entry"
-		fi
+print_cl() {
+	local package="$1"
+	changelog="$package/debian/changelog"
+
+	# Check if more than one UNRELEASED entry at top of changelog
+	Ucount=$(grep "^[^ ]" $changelog | \
+		 head -n2 | grep -c UNRELEASED)
+	if [ $Ucount -eq 1 ]; then
 		sed -n "1,/^ --/p" $changelog
-		echo; echo
-	done
-else
-	echo "$(get_list)"
-fi
+	else
+		echo "ERROR: changelog has more than one UNRELEASED entry!"
+		# Second sed is to add back a blank line between entries
+		sed -n "/^[^ ].*UNRELEASED/,/^ --/p" $changelog | \
+			sed '2,$s/^\([^ ]\)/\n\1/'
+	fi
+}
+
+first=""
+for path in $PATHS; do
+	if [ -z "$DO_CL" ]; then
+		echo "$(get_list "$path" | sed "s:^\./::")"
+	else
+		for package in $(get_list "$path"); do
+			[ -z "$first" ] || echo -e "\n====================\n"
+			first=1
+
+			print_cl "$package"
+		done
+	fi
+done
