* Joey Hess     - Fix failing exit code status logging.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@17660 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/prebaseconfig/debian/postinst b/packages/prebaseconfig/debian/postinst
--- a/packages/prebaseconfig/debian/postinst
+++ b/packages/prebaseconfig/debian/postinst
@@ -30,12 +30,13 @@ run_parts() {
             if "$script" 2> $tmpfile ; then
 		:
 	    else
-		if [ "$?" = 10 ]; then
+		code="$?"
+		if [ "$code" = 10 ]; then
 		    log "$script backed up"
     		    db_progress STOP
 		    exit 10
 		fi
-		log "warning: $script returned error code $?"
+		log "warning: $script returned error code $code"
 	    fi
 	    if [ -s "$tmpfile" ] ; then
 		logger -t prebaseconfig < "$tmpfile"
