* Improved the debian-installer.d error handling. Now it tells which      script failed and how, and only pauses if there was a real failure.    * debian-installer.d scriptlets are now required to be set -e safe (and so      audited)
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@5515 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/rootskel/src/sbin/debian-installer b/rootskel/src/sbin/debian-installer
--- a/rootskel/src/sbin/debian-installer
+++ b/rootskel/src/sbin/debian-installer
@@ -1,12 +1,11 @@
 #! /bin/sh
 # This script is called at system startup
 # This is where the installer actually interacts with the user
-
+set -e
 for script in /lib/debian-installer.d/S[0-9][0-9]*; do
-    . $script
+	. $script || (
+		echo "$script failed with exit code $?"
+		echo "Press Enter to continue."
+		read line
+	)
 done
-
-# Allow error messages to be seen if we're in a crash-loop.
-echo
-echo "Something has gone wrong. Press enter to try again."
-read line
