Correct floppy device, and try to load the floppy driver module before mounting floppies.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@1130 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/disk-detect/debian/postinst b/tools/disk-detect/debian/postinst
--- a/tools/disk-detect/debian/postinst
+++ b/tools/disk-detect/debian/postinst
@@ -27,6 +27,16 @@ do
 done
 echo $old >/proc/sys/kernel/printk
 
+load_floppy_driver() {
+    if [ ! -d /dev/floppy ] ; then
+        modprobe floppy >> /var/log/messages 2>&1 || true
+    fi
+    if [ ! -d /dev/floppy ] ; then
+        log "error: Unable to load floppy device driver"
+    fi
+    floppydev=/dev/floppy/0
+}
+
 IFS_SAVE="$IFS"
 IFS="
 "
@@ -65,7 +75,8 @@ do
                 then
                     break
                 fi
-                mount -t ext2 /dev/fd0 /mnt
+                load_floppy_driver
+                mount -t ext2 $floppydev /mnt
                 if [ "$?" = "0" ]
                 then
                     if [ -f /mnt/modules.tgz ]
@@ -121,7 +132,8 @@ then
             then
                 break
             fi
-            mount -t ext2 /dev/fd0 /mnt
+            load_floppy_driver
+            mount -t ext2 $floppydev /mnt
             if [ "$?" = "0" ]
             then
                 if [ -f /mnt/pcmcia.tgz ]
