Fail when the distribution (mirror/suite) cannot be determined. Currently, the user only finds out in base-installation.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@27034 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/cdrom-detect/debian/cdrom-detect.postinst b/packages/cdrom-detect/debian/cdrom-detect.postinst
--- a/packages/cdrom-detect/debian/cdrom-detect.postinst
+++ b/packages/cdrom-detect/debian/cdrom-detect.postinst
@@ -174,6 +174,14 @@ for distlink in stable testing unstable ; do
 	fi
 done
 
+if [ -z "$suite" ] ; then
+	log "Error reading Release file; unable to determine distribution"
+	db_input critical cdrom-detect/no-release || [ $? -eq 30 ]
+	db_go
+	umount /cdrom
+	fail
+fi
+
 # Ask for eject to be installed into /target/, to be able to use it in
 # the prebaseconfig script.
 apt-install eject || true
