Port patch from Ubuntu to check that a CD is a valid installation CD
If not, proceed to check other devices. Note that we do not check if
the CD is for the correct Debian release or even that it is for the
correct distribution (Debian vs. Ubuntu), but only if it is recognized
as some CD probably produced by debian-cd.

Also handle the "USB vfat" and "iso9660" cases the same and reduce code
duplication by factoring out a try_mount() function.

Thanks to Joshua Kwan for pointing out the Ubuntu patch.

git-svn-id: svn://svn.debian.org/svn/d-i/trunk@62667 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/cdrom-detect/debian/cdrom-detect.postinst b/packages/cdrom-detect/debian/cdrom-detect.postinst
--- a/packages/cdrom-detect/debian/cdrom-detect.postinst
+++ b/packages/cdrom-detect/debian/cdrom-detect.postinst
@@ -8,16 +8,42 @@ log() {
 	logger -t cdrom-detect "$@"
 }
 
-fail () {
+fail() {
 	log "CDROM-detect failed; unmounting CD just to be sure"
 	umount /cdrom 2>/dev/null || true
 	exit 1
 }
 
+try_mount() {
+	local device=$1
+	local type=$2
+
+	local ret=1
+	if mount -t $type -o ro,exec $device /cdrom; then
+		log "CD-ROM mount succeeded: device=$device fstype=$type"
+		if [ -e /cdrom/.disk/info ]; then
+			CDNAME=$(cat /cdrom/.disk/info)
+			log "Detected CD '$CDNAME'"
+			db_set cdrom-detect/cdrom_device $device
+			db_set cdrom-detect/cdrom_fs $type
+			ret=0
+		else
+			log "The CD in $device is not a Debian CD!"
+			umount /cdrom 2>/dev/null || true
+			WRONG=1
+		fi
+	else
+		log "CD-ROM mount failed: device=$device fstype=$type"
+	fi
+
+	return $ret
+}
+
+
 # Is a cdrom already mounted?  If so, assume it's the right one..
 mount | grep -q 'on /cdrom' && exit 0
 if [ -e /cdrom/.disk/info ]; then
-	CDNAME=`cat /cdrom/.disk/info`
+	CDNAME=$(cat /cdrom/.disk/info)
 	log "Detected CD '$CDNAME'"
 	exit 0
 fi
@@ -28,46 +54,30 @@ log "Searching for Debian installation media..."
 
 mkdir /cdrom 2>/dev/null || true
 
-while true
-do
+while true; do
 	mounted=
+	WRONG=
 
 	if db_get cdrom-detect/try-usb && [ "$RET" = true ]; then
 		devices="$(list-devices usb-partition)"
 		for device in $devices; do
-			if mount -t vfat -o ro,exec $device /cdrom &&
-			   [ -e /cdrom/.disk/info ]; then
-				log "CD-ROM mount succeeded: device=$device fstype=vfat"
-				mounted=1
-				db_set cdrom-detect/cdrom_device $device
-				db_set cdrom-detect/cdrom_fs vfat
-				break
-			else
-				log "CD-ROM mount failed: device=$device fstype=vfat"
-				umount /cdrom 2>/dev/null || true
+			if try_mount $device vfat; then
+				break 2
 			fi
 		done
 	fi
 
-	if [ "$mounted" ]; then
-		break
-	fi
-
 	devices="$(list-devices cd; list-devices maybe-usb-floppy)"
 	for device in $devices; do
-		if mount -t iso9660 -o ro,exec $device /cdrom; then
-			log "CD-ROM mount succeeded: device=$device fstype=iso9660"
-			mounted=1
-			db_set cdrom-detect/cdrom_device $device
-			db_set cdrom-detect/cdrom_fs iso9660
-			break
-		else
-			log "CD-ROM mount failed: device=$device fstype=iso9660"
+		if try_mount $device iso9660; then
+			break 2
 		fi
 	done
 
-	if [ "$mounted" ]; then
-		break
+	if [ "$WRONG" ]; then
+		db_input critical cdrom-detect/wrong-cd || [ $? -eq 30 ]
+		db_go
+		fail
 	fi
 
 	# If a device was detected but the mount failed, ask for the CD.
@@ -102,7 +112,8 @@ do
 	db_get cdrom-detect/manual_config
 
 	modules=none
-	for i in `ls -1 /lib/modules/*/kernel/drivers/cdrom/ | sed 's/\.ko$//' | sed 's/\.o$//'`; do
+	for i in $(ls -1 /lib/modules/*/kernel/drivers/cdrom/ | \
+		   sed 's/\.ko$//' | sed 's/\.o$//'); do
 		modules="$modules, $i"
 	done
     
@@ -136,16 +147,6 @@ do
 		fail
 	fi
 done
-
-if [ -e /cdrom/.disk/info ]; then
-	CDNAME=`cat /cdrom/.disk/info`
-	log "Detected CD '$CDNAME'"
-else
-	log "The available CD is not a Debian CD!"
-	db_input critical cdrom-detect/wrong-cd || [ $? -eq 30 ]
-	db_go
-	fail 
-fi
 
 # Get all the pool directories into the dentry cache, to cut down on seek
 # times.
