* Redirect any error output from the find command to the syslog,   rather than /var/log/messages.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@30745 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/cdrom-detect/debian/cdrom-detect.postinst b/packages/cdrom-detect/debian/cdrom-detect.postinst
--- a/packages/cdrom-detect/debian/cdrom-detect.postinst
+++ b/packages/cdrom-detect/debian/cdrom-detect.postinst
@@ -148,7 +148,10 @@ for pooldir in /cdrom/pool/*/*; do
 	if [ -d "$pooldir" ]; then
 		db_subst cdrom-detect/scanning_progress_step DIR "$pooldir"
 		db_progress INFO cdrom-detect/scanning_progress_step
-		find "$pooldir/" >/dev/null 2>>/var/log/messages || true
+		err=$(find "$pooldir/" 2>&1 >/dev/null) || true
+		if [ -z "$err" ]; then
+			log "find error: $err"
+		fi
 	fi
 	db_progress STEP 1
 done
