Don't call run method in case prepare fails
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@64178 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/debian-installer-launcher/plugins/live b/packages/debian-installer-launcher/plugins/live
--- a/packages/debian-installer-launcher/plugins/live
+++ b/packages/debian-installer-launcher/plugins/live
@@ -54,7 +54,7 @@ live_prepare()
 		[ -e $IMAGE ] && break
 	done
 
-	[ ! -e $IMAGE ] && echo "no suitable d-i initrd image found, aborting." && exit 1
+	[ ! -e $IMAGE ] && echo "no suitable d-i initrd image found, aborting." && return 1
 
 	echo "Loading debian-installer..."
 
@@ -65,7 +65,7 @@ live_prepare()
 	cd /live/installer
 	zcat $IMAGE | cpio -id > /dev/null 2>&1
 
-	$LIVE_TERMINAL /usr/share/debian-installer-launcher/debconf_kernel.sh
+	$LIVE_TERMINAL /usr/share/debian-installer-launcher/debconf_kernel.sh || return 1
 
 	# Preseeding shutdown command
 	cat >> preseed.cfg << EOF
