Add another fix for bug #177459 which also work on CDROM installs. (closes: #180227)
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@1907 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/tools/prebaseconfig/prebaseconfig.d/90prepare-base-config b/tools/prebaseconfig/prebaseconfig.d/90prepare-base-config
--- a/tools/prebaseconfig/prebaseconfig.d/90prepare-base-config
+++ b/tools/prebaseconfig/prebaseconfig.d/90prepare-base-config
@@ -13,29 +13,42 @@ fi
 if db_get mirror/distribution && [ "$RET" ] ; then
     SUITE="$RET"
 
-    if [ -f /cdrom/.disk/base_installable ] ; then
-	SUITE=`sed -n 's/^Suite: *//p' /cdrom/dists/$SUITE/Release`
-    else
-	db_get mirror/protocol
-	PROTOCOL="$RET"
+# This code try to fix bug #177459, but fail to work on CDROM installs
+# as /cdrom/ is umounted at this point.
+#    if [ -f /cdrom/.disk/base_installable ] ; then
+#	SUITE=`sed -n 's/^Suite: *//p' /cdrom/dists/$SUITE/Release`
+#    else
+#	db_get mirror/protocol
+#	PROTOCOL="$RET"
+#
+#	db_get mirror/$PROTOCOL/hostname
+#	MIRROR="$RET"
+#
+#	db_get mirror/$PROTOCOL/directory
+#	DIRECTORY="$RET"
+#
+#	if [ "$PROTOCOL" = "http" ]; then
+#            # try to find http proxy
+#	    db_get mirror/http/proxy
+#	    http_proxy="$RET" || true
+#	    if [ "$http_proxy" ]; then
+#		export http_proxy
+#	    fi
+#	fi
+#
+#	SUITE=`wget -O - ${PROTOCOL}://${MIRROR}${DIRECTORY}/dists/$SUITE/Release | sed -n 's/^Suite: *//p'`
+#    fi
 
-	db_get mirror/$PROTOCOL/hostname
-	MIRROR="$RET"
-
-	db_get mirror/$PROTOCOL/directory
-	DIRECTORY="$RET"
-
-	if [ "$PROTOCOL" = "http" ]; then
-            # try to find http proxy
-	    db_get mirror/http/proxy
-	    http_proxy="$RET" || true
-	    if [ "$http_proxy" ]; then
-		export http_proxy
-	    fi
-	fi
-
-	SUITE=`wget -O - ${PROTOCOL}://${MIRROR}${DIRECTORY}/dists/$SUITE/Release | sed -n 's/^Suite: *//p'`
-    fi
+    # Map from woody/sarge/sid to stable/testing/unstable, fixing bug
+    # #177459.  A better way to do this is to move the above code into
+    # cdrom-detect and perhaps choose-mirror, storing both 'woody' and
+    # 'stable' into two different debconf answers.  We need both, as
+    # debootstrap needs 'woody', while base-config needs 'stable'.
+    case "$SUITE" in 
+	woody) SUITE=stable ;;
+	sarge) SUITE=testing ;;
+	sid)   SUITE=unstable ;;
+    esac
 fi
 
 # Look in /proc/cmdline for console=ttyS*, indicating a serial console
