properly abort if the ISO is missing
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@47253 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/digress/preboot/startqemu-cdrom b/scripts/digress/preboot/startqemu-cdrom
--- a/scripts/digress/preboot/startqemu-cdrom
+++ b/scripts/digress/preboot/startqemu-cdrom
@@ -10,6 +10,11 @@ if [ -z "$QEMU_DISK" ]; then
 	QEMU_DISK=$STATE_DIR/qemu-$MACHINE-$SCHEME.img
 fi
 
+if [ ! -e "$ISO" ]; then
+	echo "ISO $ISO not found" >&2
+	exit 1
+fi
+
 # Store the pid so stopqemu can stop it later.
 echo "$$" > $STATE_DIR/qemu-$MACHINE-$SCHEME.pid
 exec $QEMU_COMMAND -cdrom "$ISO" \
