try 10 times just to be sure
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@45837 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/digress/console/console-qemu b/scripts/digress/console/console-qemu
--- a/scripts/digress/console/console-qemu
+++ b/scripts/digress/console/console-qemu
@@ -1,3 +1,12 @@
 #!/bin/sh
 set -e
-nc localhost $QEMU_SERIAL_PORT
+count=0
+while ! nc localhost $QEMU_SERIAL_PORT; do
+	count=$(expr $count + 1)
+	sleep 1
+	if [ "$count" = 10 ]; then
+		echo "Error: could not connect over $count tries" >&2
+		exit 1
+	fi
+	echo "Retrying connection.."
+done
