* Jure Cuhalev      - Add Slovenian translation (sl.po). Closes: #215420.    * K��stutis Bili��nas      - Add Lithuanian translation (lt.po).    * Claus Hindsgaul      - Add Danish translation (da.po).    * Joey Hess      - Add a progress bar to the packages scan as even this can take some time        to complete.      - Support USB floppies: If INSTALL_MEDIA_DEV is set, it was passed        from the linuxrc on the boot floppy, and points to the device the        initrd was loaded from. Or the user can set it at boot.      - This also allows something saner than "first floppy drive" in the        prompt.      - When scanning for packages, exit 1 if no files were found. Must not be a        driver floppy then.
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@5047 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/retriever/floppy/floppy-retriever b/retriever/floppy/floppy-retriever
--- a/retriever/floppy/floppy-retriever
+++ b/retriever/floppy/floppy-retriever
@@ -6,14 +6,24 @@ FLOPPYMNT=/floppy
 
 db_capb BACKUP
 
-# FIXME FIXME FIXME
 mountfloppy()
 {
     if ! mount | cut -d' ' -f3 | grep -q '^/floppy$'; then
-        if [ ! -d /dev/floppy ]; then
+	# The INSTALL_MEDIA_DEV is set by the linuxrc on the boot
+	# floppy to the device it loaded the initrd from. It's also
+	# documented so the user may set it at the boot prompt.
+	# That is (probably) the floppy drive, which may be a USB floppy.
+	if [ -n "$INSTALL_MEDIA_DEV" ]; then
+	    FLOPPYDEV=$INSTALL_MEDIA_DEV
+        else
+	    # XXX not ideal. Fails if the floppy is USB.
+	    FLOPPYDEV=/dev/floppy/0
+	fi
+	    
+        if [ ! -e $FLOPPYDEV ]; then
             modprobe floppy >> /var/log/messages 2>&1
         fi
-        if [ ! -d /dev/floppy ]; then
+        if [ ! -e $FLOPPYDEV ]; then
             exit 1
         fi
         if ! grep -q ^vfat /proc/modules ; then
@@ -27,7 +37,7 @@ mountfloppy()
         fi
         db_capb
 
-        mount /dev/floppy/0 -tauto $FLOPPYMNT
+        mount $FLOPPYDEV -tauto $FLOPPYMNT
     fi
 }
 
@@ -61,14 +71,28 @@ case "x$cmd" in
         touch "$1"
         # Check for regular debs, udebs, and to be on the safe side,
         # check for *.ude files (msdos file names...)
+	FILES=""
+	FILE_COUNT=0
         for filename in $FLOPPYMNT/*.deb $FLOPPYMNT/*.udeb $FLOPPYMNT/*.ude; do
             if [ -f "$filename" ]; then
-                udpkg -f "$filename" >> "$1"
-                path="`echo "$filename" | sed 's,^/floppy/,,'`"
-                echo "Filename: $path" >> "$1"
-                echo >> "$1"
-            fi
+	    	FILES="$FILES $filename"
+		FILE_COUNT=$(expr $FILE_COUNT + 1)
+	    fi
+	done
+	if [ "$FILE_COUNT" = 0 ]; then
+		# Probably not a legitimate driver floppy.
+		exit 1
+	fi
+	# This could take a while, so a progress bar.
+	db_progress START 0 $FILE_COUNT retriever/floppy/packages/progress
+	for filename in $FILES; do
+            udpkg -f "$filename" >> "$1"
+            path="`echo "$filename" | sed 's,^/floppy/,,'`"
+            echo "Filename: $path" >> "$1"
+            echo >> "$1"
+	    db_progress STEP 1
         done
+	db_progress STOP
         ;;
 
     xcleanup)
