install glantank-utils and run glantank-update-kernel
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@40962 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/arch/arm/glantank/debian/glantank-installer.postinst b/packages/arch/arm/glantank/debian/glantank-installer.postinst
--- a/packages/arch/arm/glantank/debian/glantank-installer.postinst
+++ b/packages/arch/arm/glantank/debian/glantank-installer.postinst
@@ -4,61 +4,28 @@ set -e
 
 . /usr/share/debconf/confmodule
 
-findfs () {
-	mount | grep "on /target${1%/} " | cut -d' ' -f1
+log() {
+	logger -t glantank-installer "$@"
 }
 
-rootfs_devfs=$(findfs /)
-bootfs_devfs=$(findfs /boot)
+error() {
+	log "error: $@"
+}
 
-if [ "$bootfs_devfs" = "" ]; then
-	bootfs_devfs=$rootfs_devfs
-	boot="boot/"
-else
-	boot=""
+
+if ! apt-install glantank-utils; then
+	error "apt-install glantank-utils failed"
+	exit 1
 fi
 
-# The name of the symlinks to be created depends on the machine
-case "`archdetect`" in
-	arm/iop32x)
-		machine=$(grep "^Hardware" /proc/cpuinfo | sed 's/Hardware\s*:\s*//')
-		if echo "$machine" | grep -q "^GLAN Tank"; then
-			kernel_alias=zImage
-			initrd_alias=initrd
-		fi
-		;;
-esac
-
-# Look for kernel and initrd
-
-db_get base-installer/kernel/linux/link_in_boot
-link_in_boot="$RET"
-if [ "$link_in_boot" = "true" ]; then
-	boot_link="boot/"
-else
-	boot_link=""
+# Set up glantank-update-kernel to run on kernel upgrades.
+if ! grep -q glantank-update-kernel /target/etc/kernel-img.conf; then
+	echo "postinst_hook = /usr/sbin/glantank-update-kernel" >> \
+		target/etc/kernel-img.conf
 fi
 
-if [ -e /target/${boot_link}vmlinuz ]; then
-	kernel="vmlinuz"
-elif [ -e /target/${boot_link}vmlinux ]; then
-	kernel="vmlinux"
-else
-	kernel=`ls /target/boot/vmlinuz-2.* | sed -e 's%/target/boot/%%' | tail -n 1`
-fi
-
-if [ -e /target/${boot_link}initrd.img ]; then
-	initrd=initrd.img
-else
-	initrd=`ls /target/boot/initrd.img* | sed -e 's%/target/boot/%%' | tail -n 1`
-fi
-
-# ... and make symlinks
-
-if [ -n "$kernel" -a -n "$kernel_alias" ]; then
-	ln -s $kernel /target/${boot_link}${kernel_alias}
-fi
-if [ -n "$initrd" -a -n "$initrd_alias" ]; then
-	ln -s $initrd /target/${boot_link}${initrd_alias}
+if ! in-target glantank-update-kernel; then
+	error "glantank-update-kernel failed"
+	exit 1
 fi
 
