- Also exclude D-I specific boot parameters - Whitespace cleanup - Add test for missing results line for user-params test - Add additional testcases for user-params
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@45331 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/packages/debian-installer-utils/testsuite/tests/user-params b/packages/debian-installer-utils/testsuite/tests/user-params
--- a/packages/debian-installer-utils/testsuite/tests/user-params
+++ b/packages/debian-installer-utils/testsuite/tests/user-params
@@ -32,6 +32,11 @@ while read line; do
 	fi
 done <user-params.tests
 
+if [ "$TESTING" ]; then
+	echo "error: missing results line"
+	exit 1
+fi
+
 if [ $TEST_VERBOSE -ge 2 ]; then
 	echo "Result: $SUCCESSES out of $TESTS test cases were successful"
 fi
